.pnp.cjs, package.json, src/app/layout.tsx, src/contexts/Providers.tsx, src/contexts/reactQuery/PrefetchHydration.tsx, src/contexts/reactQuery/QueryClientProvider.tsx, yarn.lock
- react-query 관련 라이브러리 설정
- app 디렉토리 기반 react-query 프로젝트 설정
- QueryClientProvider 추가
- prefetch & hydration 방식을 사용해서 SSR 구현 [[참고 공식 문서 - advanced ssr]](https://tanstack.com/query/v5/docs/react/guides/advanced-ssr)
prefetch 사용 방식은 아래 예시를 참고하시면 됩니다!
``` tsx
// Usage
import PrefetchHydration from '@/contexts/reactQuery/PrefetchHydration';
const Page = () => {
return (
<PrefetchHydration
queryKey={['foo']}
queryFn={() => fetch('/bar'))}
>
<List />
</PrefetchHydration>
);
};
const List = () => {
const { data } = useQuery({
queryKey: ['foo'],
queryFn: () => fetch('/bar')
});
...
};
```
=> chore: @tanstack/react-query 설정

.eslintrc.json, .pnp.cjs, src/app/globals.css, src/app/layout.tsx
- [task](https://www.notion.so/depromeet/layout-a2f156d089b04768bd8359e51ea90096) : 기본 layout size를 지정합니다.
- max-width: 520px / min-height: 100dvh
- [dvh 관련 reference](https://mong-blog.tistory.com/entry/CSSJS-vh-%EB%B2%84%EA%B7%B8-%ED%95%B4%EA%B2%B0%EB%B0%A9%EB%B2%95dvh-%EC%82%AC%EC%9A%A9%EB%B2%95-js-%EA%B3%84%EC%82%B0%EB%B2%95) 보고 저희 서비스에 사용해도 좋을 거 같아서 적용했습니다 😆
- tailwind의 동적으로 할당하는 방식의 제한이 있어서 해당 코드 형태로 뺐습니다,, 해당 방식이 추후 유지보수면에서 사알짝 마음에 걸리긴 해서 더 좋은 의견이 있으시면 마구마구 부탁드립니다 🙏 !
➕ 아 !! 그리고 JSX에서 불필요한 중괄호를 없애는 lint rule도 스을쩍 추가해보았습니다,, (제 픽 삶의질 향상 린트 룰,,)
=> chore: 기본 layout size 지정

src/components/atoms/index.ts, src/components/atoms/tag/Tag.stories.tsx, src/components/atoms/tag/Tag.tsx, src/components/atoms/tag/index.ts
- TagForm에 들어가는 Tag 컴포넌트 개발
- `isFocus`에 true를 넘겨주면 오른쪽 같이 스타일링됩니다 🕺 (왼: false, 오: true)
- N/A
=> feat: Tag 컴포넌트 추가

src/app/page.tsx
- 빌드되고 보니까 lazy loading이 되어서 priority 부여했습니다.
- 해당 Image 컴포넌트에 priority 속성 부여
- N/A
=> chore: 반디부디 이미지에 priority 부여

src/middleware.ts
- 쿠키에 accessToken이 존재하지 않을 경우, 로그인 화면으로 redirection
- middleware를 통해 matcher에 등록된 page에 접근시 request의 cookie에 accessToken이 존재하는지 판별하여 redirection
- N/A
=> feat: accessToken이 존재하지 않을 경우, 로그인 화면으로 redirection

src/hooks/reactQuery/auth/index.ts, src/hooks/reactQuery/auth/useCreateMemberData.ts, src/hooks/reactQuery/goal/index.ts, src/hooks/reactQuery/goal/useCreateGoal.ts, src/hooks/reactQuery/goal/useDeleteGoal.ts, src/hooks/reactQuery/goal/useGetGoal.ts, src/hooks/reactQuery/goal/useGetGoals.ts, src/hooks/reactQuery/sticker/index.ts, src/hooks/reactQuery/sticker/useGetStickers.ts, src/hooks/reactQuery/tag/index.ts, src/hooks/reactQuery/tag/useGetTags.ts
- api hook 구현
- goal / tag / sticker / auth api hook 구현 
- swagger를 기준으로 작성해서 추후 변경 사항이 있을 수 있습니다
- query
``` ts
const { data: tags } = useGetTags();
```
- mutation
``` ts
const { mutate: createGoal } = useCreateGoal();
const handleSubmit = () => {
const payload = {
title: 'string',
yearOfDeadline: '2023',
monthOfDeadLine: '12',
stickerId: 2,
tagId: 1,
description: 'string',
};
createGoal(payload);
};
```
- 타입 분리 리팩토링
=> feat: goal / tag / sticker / auth api hook 구현 

src/components/atoms/tag/Tag.tsx, src/features/goal/components/new/TagForm.tsx, src/features/goal/types/form.ts
- goal 추가 화면의 tag 추가 기능 구현
- react-query 반영된 tag입니다.
https://github.com/depromeet/amazing3-fe/assets/34956359/151c3cbe-5181-47bd-a568-7131b2419b09
=> feat: goal 추가 화면의 tag 추가 기능 구현

src/features/auth/components/GoogleLoginButton.tsx
- rewrites 경로를 타면서 oauth 경로가 변경되는 문제 발생
- 경로를 직접 주입하는 방식으로 문제 해결
- N/A
=> chore: OAuth 연동 이슈 해결

src/app/member/new/birth/page.tsx, src/app/member/new/birthday/page.tsx, src/features/member/components/new/BirthInputForm.tsx, src/features/member/components/new/BirthdayInputForm.tsx, src/features/member/components/new/NicknameInputForm.tsx, src/features/member/components/new/index.ts, src/features/member/contexts/NewMemberFormProvider.tsx, src/features/member/types/form.ts
- 구글 로그인을 통해 처음 접근한 유저를 서버에 등록하는 API를 연결
- 민경님께서 구현해주신 React Query Hook을 사용하여 사용자가 입력한 데이터를 서버에 등록을 요청하는 API를 연결
- 서버쪽에서 `birth`라는 이름으로 생년월일을 저장하고 있어서 클라이언트도 `birthday` -> `birth`로 변경하였습니다!
=> feat: 새로운 유저 등록 API (PUT "/my") 연결

src/app/login/oauth2/code/google/page.tsx, src/features/home/components/lifeMap/LifeMap.tsx, src/features/home/components/mapCardPositioner/MapCardPositioner.utils.ts, src/hooks/reactQuery/goal/useDeleteGoal.ts
- goal이 없는 경우 에러 발생
- delete 시 500 에러 발생
- 위 내용 해결 반영
-
=> Bug: new member로 등록 시 발생하는 버그 수정

src/features/goal/components/detail/SavedFooterButton.tsx, src/features/goal/components/detail/SavedHeader.tsx, src/features/member/contexts/NewMemberFormProvider.tsx
- react-query 최적화 전 임시 해결책 반영
- 
-
=> bug: 페이지 리프레시를 위한 코드 수정

src/features/home/components/lifeMap/LifeMap.tsx, src/features/home/components/mapCardPositioner/MapCardPositioner.tsx, src/features/home/components/mapCardPositioner/MapCardPositioner.utils.ts
- 홈화면 MapCard 제대로 렌더링되지 못한 이슈 해결
- 로직 수정
-
=> bug: 홈화면 MapCard 제대로 렌더링되지 못한 이슈 해결

src/features/home/components/lifeMap/LifeMap.tsx, src/features/home/components/mapCardPositioner/MapCardPositioner.tsx, src/hooks/reactQuery/goal/useCreateGoal.ts, src/hooks/reactQuery/goal/useGetGoals.ts
- 목표 추가 후 invalidQueries가 제대로 동작하지 못한 이슈 발견
- gcTime: 0 추가
- N/A
=> bug: invalidQueries 동작 관련 이슈 해결

src/features/home/components/MapCardCollections/EmptyMapCard/EmptyMapCard.tsx, src/features/home/components/MapCardCollections/MapCardLayout.tsx, src/features/home/components/MapCardCollections/StartMapCard/StartMapCard.tsx, src/features/home/components/lifeMap/LifeMap.tsx, src/hooks/reactQuery/goal/useCreateGoal.ts
- 의도한 상황과 달리 edge가 생성되는 문제가 있었습니다.
- split된 배열의 길이를 통해 `LAST_PAGE`를 지정했습니다.
- 추가로 만혁센세이가 언급하신 클릭 이벤트 없는 card에 cursor-default 적용했습니다 ^_^ㅠ
- N/A
=> bug: 홈화면 edge 이슈 해결

src/app/globals.css, src/app/goal/new/layout.tsx, src/app/home/layout.tsx, src/app/member/new/layout.tsx, src/app/onboarding/layout.tsx, src/app/page.tsx, src/features/customErrors/components/errorPageLayout/ErrorPageLayout.tsx, src/features/home/components/lifeMap/LifeMap.tsx
=> bug: dvh 적용

src/app/globals.css
=> bug: 배경색 auto

src/app/page.tsx
=> bug: 홈화면 레이아웃 조정

src/features/goal/components/new/MoreForm.tsx
- 제곧내  (이게 찐막...!!)
- 
https://github.com/depromeet/amazing3-fe/assets/34956359/96b0fedb-aed9-45a3-b237-1c363b6d7777
=> bug: 버튼 클릭 시 응답받기 전까지 스피너 출력

.pnp.cjs, next.config.js, package.json, sentry.client.config.ts, sentry.edge.config.ts, sentry.server.config.ts, src/app/global-error.tsx, yarn.lock
- 클라이언트에서 발생하는 오류를 트래킹 하기 위해 sentry를 추가했어요
- ios, android, web 브라우저마다 다르게 동작하는 부분을 추적하기 쉽지 않을까해서 추가해봤습니다~
- https://bandiboodi.sentry.io/ 
- amazingdpm 계정으로 sentry에 접속하면 발생한 에러를 모니터링할 수 있어요
- [sentry 공식문서](https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/?original_referrer=https%3A%2F%2Fwww.google.com%2F) 그대로 설정했어요
- production 에러 캡쳐
- 전역 에러 캡쳐
- 에러 캡쳐는 추후에 api 에러 핸들링이나 중요한 기능에만 넣는 걸로 변경해도 좋을 것 같아요
---
sentry에 대해 소개를 간단히 해보자면..
- 에러 종류와 설명
- IP주소, Browser 정보, Device 정보, OS 정보 확인 가능
- 에러 발생한 환경이랑 실제 소스코드에서 어디가 에러 발생한 부분인지 트래킹하기 아주 좋습니다..
- 에러 발생하면 슬랙에 노티 오게 하려고 했는데 채널을 못찾네요 🥹
=> chore: sentry 추가

src/features/goal/components/new/DateInput.tsx, src/features/member/contexts/NewMemberFormProvider.tsx
- 제곧내
- 
- 정상동작 확인
https://github.com/depromeet/amazing3-fe/assets/34956359/de215bd6-7d4c-474e-a731-f32d191f9d00
=> [긴급] bug: Birth Day 입력 필드에서 잘못 설정된 포맷 수정

src/hooks/reactQuery/goal/useGetGoals.ts
=> feat: api 변경 내용 반영

src/features/home/components/lifeMap/LifeMap.tsx, src/features/member/types/form.ts, src/features/my/components/MyPageLayout.tsx, src/features/my/components/userProfile/UserInfo.tsx, src/features/my/components/userProfile/UserProfile.tsx, src/features/my/utils/getDateDiffFromToday.ts, src/features/my/utils/index.ts
- [마이페이지 제작 (우선순위 별로 가능한 만큼만 진행)](https://www.notion.so/depromeet/4013b0601dac4f1dbc70b627e48bfe10?pvs=4)
- API 연결
- 바뀐 API 명세에 따라 `MemberProps`를 수정
- 민경님께서 만들어주신 react query hook 중 useGetMemberData를 사용
- 입력받은 날짜와 오늘 날짜 사이의 일수를 구하는 util 함수 구현
- N/A
=> feat: 마이페이지 API 연결

next.config.js
- 테스트 환경에서 카카오 로그인 시 프로파일 이미지 출력 안되는 이슈 발견
- 카카오 로그인 심사를 위한 테스트 계정 프로파일 출력 시 필요한 경로 추가
- N/A
=> bug: kakao 이미지 호스팅 경로 수정

src/features/goal/components/detail/AddTaskInput.tsx
- 화면 크기가 작아지면 세부 목표 input이 일부 가려지는 문제
- max width를 주어 해결했습니다.
https://github.com/depromeet/amazing3-fe/assets/112946860/05b5c1ef-3355-4014-8d0e-55ab587b25cc
죄성합니다 😓,,,
=> bug: 세부목표 Input 가려지는 문제 해결

src/components/atoms/toast/ToastProvider.tsx
- [비슷한 이슈](https://github.com/radix-ui/primitives/issues/1386) 확인해서 반영했습니다.
- Portal이 DOM을 건드리는 애여서 SSR 과정에서 에러가 났나봅니다 ㅠ;
- 'use client'로는 해결이 안 되어서 이슈 보고 해결했섬니다.
=> bug: Portal에서 hydration 이슈 해결

src/features/goal/components/new/GoalForm.tsx, src/features/goal/components/new/GoalGuideBottomSheet.tsx, src/features/goal/components/new/TextInput.tsx, src/features/my/components/update/UpdateForm.tsx
- [가이드 선택 후 textField 터치/클릭 시 사라짐](https://www.notion.so/depromeet/textField-cf28b2e015be4f6999b3031aad951d07?pvs=4)
- [가이드 선택했음에도 textField에 들어가지 않음](https://www.notion.so/depromeet/textField-1937177c36a84de9b7424d9ea6a84399?pvs=4)
- textfield 잘못 변경된 내용 원복 및 불필요한 코드 삭제
https://github.com/depromeet/amazing3-fe/assets/34956359/28f3913f-2aff-44cf-9c99-38e78c1b90f3
-
=> bug: GoalForm에서 textfield 반영 안되는 문제 해결

next.config.js
=> fix: 네이버 프로필 이미지 도메인 추가

src/features/my/components/update/UpdateForm.tsx
- my page에 form 업데이트 로직 수정
- 
-
=> bug: form 값이 없을 때 버그 수정

src/app/oauth2/token/page.tsx, src/features/home/components/lifeMap/LifeMap.tsx, src/features/my/components/logoutBottomSheet/Footer.tsx
=> fix: 나만보기 인생지도로 조회 시, 500에러 수정

src/app/layout.tsx
- [IOS로 세부목표 수정시 화면 비율 조정 필요](https://www.notion.so/depromeet/IOS-756d79837e7842aeb2098368e95f908b)
- viewport 추가 ([레퍼런스](https://devsoyoung.github.io/posts/ios-input-focus-zoom/))
|:--:|:--:|
| <video src="https://github.com/depromeet/amazing3-fe/assets/112946860/59e86c14-3a0e-4094-bf93-6f65e9c2bfc1" /> | <video src="https://github.com/depromeet/amazing3-fe/assets/112946860/13bd3102-1699-43fe-b777-f62a1bd77123" /> |
=> bug: ios에서 input 포커스될 때 화면이 확대되는 이슈 해결

src/features/member/components/new/BirthInputForm.tsx, src/features/member/components/new/NicknameInputForm.tsx, src/features/my/components/withdrawBottomSheet/Footer.tsx
- 텍스트 이상하다는 피드백 반영
- `beta에서는 생년월일을 수정할 수 없어요.` -> `생년월일은 마이페이지에서 수정할 수 있어요.`
- `beta에서는 닉네임을 수정할 수 없어요.` -> `닉네임은 마이페이지에서 수정할 수 있어요.`
- `준비중인 기능입니다!` -> `준비 중인 기능입니다. 지금 탈퇴를 원하시면 피드백 보내기를 통해 요청해 주세요.`
- N/A
=> bug: 불필요한 텍스트, 이상한 텍스트 수정

src/components/atoms/bottomSheet/BottomSheet.tsx, src/components/molecules/selectableCardList/SelectableCardList.tsx, src/features/goal/components/new/GoalGuideBottomSheet.tsx
- [[목표 가이드] 바텀시트](https://www.notion.so/depromeet/7594012b16f443648831b8f64d356b8a?pvs=4) 
- [바텀시트 높이 고정 필요](https://www.notion.so/depromeet/4006bf64a5ea44c98235d3e2a89f63b6?pvs=4)
|:--:|:--:|
| <video src="https://github.com/depromeet/amazing3-fe/assets/34956359/fdcee068-32d8-4d94-88f9-93fa884eb1b2" /> | <video src="https://github.com/depromeet/amazing3-fe/assets/34956359/40e7c6da-671b-492c-9c19-b7ec83807d5e" /> |
-
=> bug: bottom sheet content 스크롤 비정상 동작하는 문제 해결

src/features/customErrors/components/errorPageLayout/ResetButton.tsx, src/features/home/components/lifeMap/LifeMap.tsx, src/features/home/components/lifeMap/PublicLifeMap.tsx, src/features/my/components/MyPageLayout.tsx, src/hooks/useIsMyMap.ts
- [마이페이지에서 url 복사 → 공유한 경우](https://www.notion.so/depromeet/url-cdb4b2c367c943c587c8e0bfe82f4e5d?pvs=4)
- [로그인 한 상태로 비공개 지도 접근 → 하단 버튼 클릭 시 스플래시가 아니라 내 지도로 이동하도록](https://www.notion.so/depromeet/8a2486585181442f8a837489cb4a13a3?pvs=4)
- [나만보기한 내 인생지도 → 내 목표 조회 실패](https://www.notion.so/depromeet/58c165fc96ab4cac97f1c6f8e530e33f?pvs=4) 
- [bug: 로그인 안한 상태로 my 페이지 접근 시 / 경로로 redirect](https://github.com/depromeet/amazing3-fe/commit/b1fc0fe94bf2d84808cb8b51b5200b45182a26d5)
- [bug: 처음 isMyMap 값이 false로 시작되어 open/life-map이 호출되는 문제 해결](https://github.com/depromeet/amazing3-fe/commit/2e0f38d3609b2845dc461e393b25abb5f17bfa98)
- localStorage가 없는 경우를 잡기 위해 useEffect 사용
- [bug: 403 에러 시 로그인 여부에 따라 바로가기 링크 제공](https://github.com/depromeet/amazing3-fe/commit/f7154edf59987d99dc93e3ba19251da66810a312) …
=> bug: url로 직접 접근 시 버그 수정 (지도 공유, 마이페이지) 

src/features/my/components/update/ProfileImageBottomSheet.tsx
- 너무 성의 없는 profile 선택 bottom sheet.. 조금 성의있게 변경
|:--:|:--:|
| ![스크린샷 2024-01-28 212645](https://github.com/depromeet/amazing3-fe/assets/34956359/ba028985-dfc9-4b6a-b58b-c980b598de8f) | ![스크린샷 2024-01-28 212616](https://github.com/depromeet/amazing3-fe/assets/34956359/67c96ed5-6a11-40eb-a47d-fbf1a6873dfa) |
-
=> style: 3 cols -> 2 cols로 디자인 변경

src/features/home/components/lifeMap/PrivateLifeMap.tsx, src/features/home/components/shareBottomSheet/ImageDownloadBottomSheet.tsx, src/features/home/components/shareBottomSheet/ShareBottomSheet.tsx, src/features/home/components/shareBottomSheet/ShareBottomSheetFooter.tsx
- [공유 바텀시트 겹침 이슈](https://www.notion.so/depromeet/ddd67a92757f49a492f7d59280849eaf?pvs=4)
https://github.com/depromeet/amazing3-fe/assets/80238096/12e2a2d1-773b-47e1-8ba8-691e504a25f6
=> fix: 공유 바텀시트 겹침 이슈 해결

src/middleware.ts
- 배포 환경에서 공유 url로 접속 시 / 경로로 돌아가는 이슈 발견
- next에서 accesssToken 있는지 체크하는 로직 삭제
-
=> bug: 불필요한 accessToken 체크 로직 삭제

src/features/home/components/loginBottomSheet/LoginBottomSheet.tsx
- 로그인 바텀시트 배경 허여멀건 한거 왜 아무도 말 안 했어..
| AS-IS | TO-BE | 
|:--:|:--:|
| ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/dd342841-4c72-4e28-898a-28b9938feaf6) | ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/2a75ccbc-2fe7-4d2c-971e-802bc2309e2b) | 
- N/A
=> chore: 로그인 바텀시트에 css 적용

src/features/home/components/loginBottomSheet/LoginBottomSheet.styles.css
- 조ㅣ송합니다....🙏😓 모바일로 보니까 반디부디가 보랗게 질려가지고
|:--:|:--:|
| ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/38aaa45c-06a2-43e8-bf96-c6f27bced98d) | ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/43e80620-4ee7-4262-bed6-a528cef21f9c) |
- N/A
=> chore: 로그인 바텀시트 스타일 수정

src/features/home/components/loginBottomSheet/LoginBottomSheet.tsx
=> fix: botttomSheet 전체에 적용된 css 아예 제거

src/components/atoms/input/Input.tsx, src/features/goal/components/new/FormHeader.tsx, src/features/goal/components/new/GoalForm.tsx, src/features/home/components/lifeMap/LifeMapContent.tsx, src/features/member/components/new/NicknameInputForm.tsx, src/features/my/components/update/ProfileImageButton.tsx
-  input 필드 선택 후 enter press 시 의도하지 않은 버튼이 클릭되는 이슈 해결
- 버튼 tag에 명시적으로 `type='button'` 적용.
- 다음, submit 버튼은 기존처럼 enter press 시 호출되도록 통일.
- 추가적으로 life-map 현재 position이 0인 경우 현재 위치 표시 안되는 문제 발견해서 같이 수정했습니다~
https://github.com/depromeet/amazing3-fe/assets/34956359/ad704548-0427-4030-9a7d-c8894b239f64
- N/A
=> bug: input 필드 선택 후 enter press 시 의도하지 않은 버튼이 클릭되는 이슈 해결

src/app/home/[username]/layout.tsx, src/app/home/[username]/twitter-image.tsx, src/utils/getMetadata.ts
- 제곧내
- ogImage가 dynamic일 경우 ogImage 관련 설정을 하지 않도록
- 이게 맞는 방법일지는 모르겠슴..
-
=> bug: 홈화면 ogImage 보이지 않는 이슈 해결

src/utils/getMetadata.ts
=> bug: og에서 url 수정

src/app/home/[username]/layout.tsx, src/app/layout.tsx, src/utils/getMetadata.ts
=> chore: meta 및 og 원복

src/hooks/reactQuery/cheering/useGetCheerer.ts
- /my/cheering 화면에서 새로고침 시 500에러 발생 
-  응원 리스트 요청 시 undefined가 아닌 경우에만 호출하도록 수정
-
=> bug: 응원 리스트 요청 시 undefined가 아닌 경우에만 호출하도록 수정

src/app/home/[username]/layout.tsx, src/app/my/cheering/page.tsx, src/app/oauth2/token/page.tsx, src/app/page.tsx, src/atoms/index.ts, src/atoms/isLoggedIn.ts, src/components/atoms/bottomSheet/BottomSheet.tsx, src/components/atoms/input/Input.tsx, src/components/atoms/toast/ToastProvider.tsx, src/components/molecules/infiniteScroll/InfiniteScroller.tsx, src/components/molecules/selectableCardList/SelectableCardList.tsx, src/components/molecules/tabs/Tabs.tsx, src/features/auth/atom/index.ts, src/features/cheering/Cheerer.tsx, src/features/cheering/CheererCount.tsx, src/features/cheering/CheererHeader.tsx, src/features/cheering/CheererList.tsx, src/features/cheering/index.ts, src/features/goal/components/new/GoalGuideBottomSheet.tsx, src/features/home/components/MapCardCollections/EmptyMapCard/EmptyMapCard.tsx, src/features/home/components/MapCardCollections/MapCard/MapCard.tsx, src/features/home/components/lifeMap/PublicLifeMap.tsx, src/features/my/components/MyPageLayout.tsx, src/features/my/components/logoutBottomSheet/Footer.tsx, src/hooks/index.ts, src/hooks/reactQuery/auth/useGetMemberData.ts, src/hooks/reactQuery/goal/index.ts, src/hooks/reactQuery/goal/useGetGoals.ts, src/hooks/useAuth.ts, src/hooks/useIsMyMap.ts
- 응원하기 성공 시에도 toast("1분 뒤에 응원할 수 있어요.") 뜨는 이슈
- 리팩터링도 같이 해보았어요 🫡
|:--:|:--:|
| <video src="https://github.com/depromeet/amazing3-fe/assets/112946860/84ce2c97-dfa8-4f4c-a9bd-9b5411416bae" /> | <video src="https://github.com/depromeet/amazing3-fe/assets/112946860/f50e650f-58fb-4afc-8b02-2bb344cf5c0e" /> |
- N/A
=> bug: 응원하기 성공 시에도 toast 뜨는 이슈 해결

.github/workflows/chromatic.yml
- 스토리북 배포 `dev` 브랜치 추가
- 도은 소녀가 작성한 스토리가 하나도 보이지 않습니다 ..
- `dev`에 신규 피처들 들어갈거니까 추가하면 좋을 것 같아요~
-
=> chore: 스토리북 배포 dev브랜치 추가

src/features/home/components/lifeMap/PublicLifeMap.tsx
- [정책](https://www.notion.so/depromeet/Weekly-17-1-5995494d2ab24f4e943b1be0aabb68e2?pvs=4#9b3b5cd0e0604039a3d742d94f73a857) 논의 후 다시 드가기 위해 일단 복구 했어용 (갓홍석 무한감사 .,🙏)
- 응원하기는 `memberData.nickname`이 존재하는 경우에만 할 수 있도록
- N/A
=> chore: memberData.nickname이 존재하는 경우에만 응원하기 가능하도록

.github/workflows/chromatic.yml, src/features/goal/atom/index.ts, src/features/goal/atom/isMyGoal.ts, src/features/goal/components/detail/GoalDetailContent.tsx, src/features/goal/components/detail/Tasks.tsx, src/features/goal/components/detail/task/Task.tsx, src/hooks/reactQuery/goal/useGetGoal.ts
- **다른 사람의 지도에 방문했을 때**, task 컴포넌트 디자인 추가
|:--:|:--:|
| ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/38c319c2-7768-4980-be21-2bb461ba04a7) | ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/3a6668ec-8676-4405-a83d-1dec984cec4b) |
🚨 내 지도의 세부목표를 볼 때는 변경없습니다!
- N/A
=> chore: 추가된 Task 컴포넌트 디자인 적용 (타인 지도의 task)

src/app/oauth2/token/page.tsx, src/features/member/components/new/NicknameInputForm.tsx
- onboarding 화면으로 안들어가는 문제 발견
- nickname에 default 값이 들어감에 따른 redirection 로직 수정
[변경 후 유저 플로우]
https://github.com/depromeet/amazing3-fe/assets/34956359/0ed47de6-d1e4-41b4-b69f-bd81493d1639
-
=> bug: onboarding 화면으로 안들어가는 문제 해결

src/features/feed/FeedBody.tsx, src/hooks/reactQuery/goal/useGetGoalFeeds.ts
- 피드 페이지 무한 스크롤 적용
- React Query의 infiniteQuery와 InfiniteScroller를 이용하여 구현
https://github.com/depromeet/amazing3-fe/assets/45158550/bacd3825-116d-486e-80ca-e48122003157
- N/A
=> feat: 피드 페이지 무한 스크롤 적용

src/components/molecules/countEmoji/CountEmoji.stories.tsx, src/components/molecules/countEmoji/CountEmoji.tsx, src/components/molecules/index.ts, src/components/molecules/skeleton/Skeleton.stories.tsx, src/components/molecules/skeleton/Skeleton.tsx, src/components/molecules/skeleton/index.ts, src/features/comment/CommentBottomSheetLayout.tsx, src/features/comment/styles/CommentBottomSheetLayout.styles.css, src/features/emoji/BottomSheet/Content.tsx, src/features/emoji/BottomSheet/ReactUser.tsx, src/features/emoji/BottomSheet/ReactUserBottomSheet.tsx, src/features/goal/atom/goalId.ts, src/features/goal/atom/index.ts, src/features/goal/components/detail/GoalDetailContent.tsx, src/features/goal/components/detail/emoji/Emojis.tsx, src/features/goal/components/detail/emoji/ReactedEmojis.tsx, src/features/goal/components/detail/emoji/Reaction.tsx, src/features/goal/components/detail/emoji/ReactionUserTotalCount.tsx, src/hooks/reactQuery/emoji/index.ts, src/hooks/reactQuery/emoji/useCreateEmoji.ts, src/hooks/reactQuery/emoji/useDeleteReactedEmoji.ts, src/hooks/reactQuery/emoji/useGetAllEmoji.ts, src/hooks/reactQuery/emoji/useGetEmojiByGoal.ts
- 이모지 api 연동
https://github.com/depromeet/amazing3-fe/assets/112946860/2b5a0147-980e-411a-833d-618ca6dc8b85
=> feat: 이모지 api 연동

src/hooks/reactQuery/emoji/useCreateEmoji.ts
- 설레발 낙관적 업데이트 때문에 에러가 처리되지 못한 문제가 있었어유
|:--:|:--:|
| <video src="https://github.com/depromeet/amazing3-fe/assets/112946860/ee03a07b-c937-48e4-b55e-22ef1387751a" /> | <video src="https://github.com/depromeet/amazing3-fe/assets/112946860/6be5d521-80f9-4995-be35-c62f09f78cac" /> |
- N/A
=> bug: 이모지 추가 로직 중 낙관적 업데이트 제거

src/components/molecules/contentWrapper/ContentWrapper.tsx, src/features/home/components/MapCardCollections/MapCard.tsx, src/features/home/components/lifeMap/LifeMapInfo.tsx, src/hooks/reactQuery/goal/useGetGoals.ts
- close #207 
- 내 지도 ui 개선
- 단순 텍스트, 스타일만 수정했섭니다
=> chore: 내 지도 스타일 변경

src/app/feed/page.tsx, src/app/home/[username]/layout.tsx, src/app/my/page.tsx, src/components/molecules/bottomNavigation/BottomNavigation.tsx, src/components/molecules/contentWrapper/ContentWrapper.tsx, src/features/emoji/BottomSheet/Content.tsx, src/features/emoji/BottomSheet/Header.tsx, src/features/emoji/BottomSheet/ReactUserBottomSheet.tsx, src/features/feed/FeedBody.tsx, src/features/goal/components/detail/emoji/Reaction.tsx, src/features/home/components/MapCardCollections/MapCard.tsx, src/features/home/components/lifeMap/LifeMapContent.tsx, src/features/home/components/lifeMap/LifeMapInfo.tsx, src/features/home/components/lifeMap/PublicLifeMap.tsx, src/features/my/components/MyPageHeader.tsx, src/features/my/components/MyPageLayout.tsx, src/hooks/reactQuery/emoji/useCreateEmoji.ts, src/hooks/reactQuery/emoji/useGetEmojiByGoal.ts, src/hooks/reactQuery/goal/useGetGoals.ts
- close #216 
https://github.com/depromeet/amazing3-fe/assets/80238096/c842cc35-3a4d-4253-b142-6e87f7ce6ca2
| 피드 페이지 | 마이 페이지 |
| <img width="517" alt="스크린샷 2024-03-17 오전 1 23 23" src="https://github.com/depromeet/amazing3-fe/assets/80238096/284848e8-a8e0-41d7-9756-5fe7ffbc1fbd"> | <img width="514" alt="스크린샷 2024-03-17 오전 1 22 59" src="https://github.com/depromeet/amazing3-fe/assets/80238096/b7d06611-40b1-4e66-a000-3abda636e909"> |
-
=> feat: 피드 페이지 / 마이 페이지에 바텀 네비게이션 추가

src/features/home/components/timeline/Timeline.tsx, src/features/home/components/timeline/TimelineCard.tsx, src/features/home/components/timeline/TimelineCardBody.tsx, src/hooks/reactQuery/goal/useGetTimeline.ts
- 기존에 타임라인에서 사용하던 피드 api를 -> 타임라인 조회 api로 변경하였습니다
- 타임라인 조회 api 적용
https://github.com/depromeet/amazing3-fe/assets/80238096/cb0e5ca1-d351-44fd-81fe-e782ade82d69
- 피드쪽 코드 무지성으로 복사해와서 .. 추후 수정이 필요합니다..
~~다른사람 타임라인 조회도 가능해야되는데 현재 api에는 내 타임라인만 조회 가능~~
- ~~api 수정되면 반영하겠섭니다~~ -> 반영 완
=> feat: 타임라인 조회 api 반영

src/features/feed/FeedBody.tsx, src/hooks/reactQuery/emoji/useCreateEmojiForFeed.ts, src/hooks/reactQuery/emoji/useDeleteReactedEmojiForFeed.ts
- 피드 이모지 추가 / 삭제시 이모지가 늦게 추가되거나 늦게 사라지는 등의 어색함이 존재함
- 낙관적 업데이트 적용
- 앵간하면 오류는 잘안나는 것 같은데 진짜 빨리 다다다다다닥 누르면 500뜸..
- 값 없는데 삭제해달라고 하거나 값 있는데 또 추가해달라고 해서 그런듯;
- 디바운싱이 필요할까??
https://github.com/depromeet/amazing3-fe/assets/45158550/a3866348-09b6-4692-9935-70939b146924
=> feat: 피드 이모지 추가/삭제시 낙관적 업데이트 적용

src/features/comment/CommentsBottomSheet.tsx, src/features/goal/components/detail/comment/AddCommentButton.tsx, src/hooks/reactQuery/comment/useGetHasNewComment.ts
- [새로운 댓글 조회 빨간색불 의도대로 동작 X](https://www.notion.so/depromeet/X-880e713f41e942e8aa1e812567d51071?pvs=4)
|:--:|:--:|
| <video src="https://github.com/depromeet/amazing3-fe/assets/112946860/ed66c981-d9af-4a56-bca3-b9d19007ff25" /> | <video src="https://github.com/depromeet/amazing3-fe/assets/112946860/435be022-3fac-4889-9dc8-28d7bed8abb4" /> |
- N/A
=> bug: 댓글 리스트 조회 시 빨콩(HasNewComments) 바로 없어지지 않는 문제 해결

src/features/comment/BottomSheet/Content.tsx, src/features/goal/components/detail/GoalDetailContent.tsx
👇 댓글 삭제하다보면 자주 이런 에러가 남..
- 조건부 연산자 끼워넣기 했습니당
- N/A
=> bug: goalContent에서 나는 undefined 에러 대응

src/features/goal/components/detail/DetailHeader.tsx
- cursor: default로 보이던 문제
- button 래핑했어유~
- 아. . . 기회되면 IconButton 이런 거 리팩터링 하고 싶다. . . 맨날 Icon 쓸 때 버튼 래핑함 !!!! 
- N/A
=> fix: cursor default로 보이던 문제 해결

src/hooks/reactQuery/goal/useGetPublicTimeline.ts, src/hooks/reactQuery/goal/useGetTimeline.ts
- 타임라인 무한 스크롤이 안되는 이슈 수정
- 커서 기반 무한스크롤에서 -> 페이지 기반 무한스크롤 변경
-
=> fix: 타임라인 무한 스크롤이 안되는 이슈 수정

src/features/my/contexts/UpdateMemberDataFormProvider.tsx
- 아이디가 BANDIBOODI- 로 시작하는 경우, 다른 값들 수정이 안되는 문제
- 아이디 변경 사항이 없는 경우, 아이디 체크 로직 삭제
-
=> fix: username 변경 사항이 없는 경우 체크 로직 무시

src/features/feed/feedCard/FeedCardBody.tsx, src/features/home/components/timeline/TimelineCardBody.tsx
- 텍스트가 넘쳐서 보이는 문제가 있었어유
- 디자인 시안에 맞게 수정했어유
|:--:|:--:|
| ![IMG_8728](https://github.com/depromeet/amazing3-fe/assets/112946860/9769d4b5-1bd0-4bcc-aae6-41694c9a9e32) | ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/3003bb79-28f2-402a-9f4e-5c40ffc60f47) |
- N/A
=> fix: 디자인 시안에 맞게 텍스트 수정
