depromeet/amazing3-fe

src/apis/index.ts, src/app/login/oauth2/code/google/page.tsx, src/app/page.tsx
- 서버가 발급한 JWT token을 발급 받음
- 발급 받은 토큰을 헤더에 담아 사용자 데이터 요청
- 서버에서 query string으로 JWT token을 발행
- 서버에서 구글로부터 access token을 발급 받은 후 새롭게 JWT token을 발행하고 redirect를 통해 token을 전달해야해서 현재 query string을 이용한 전달 방법 밖에 찾자 못했습니다. 혹시 다른 방법을 아신다면 코멘트 주세요!
- 이후 token과 사용자 정보를 저장하는 로직을 추가해야 합니다! 
- 이전 PR 닫고 새로 브랜치 따서 다시 올렸습니다~~
=> feat: token 발행 후 사용자 데이터 접근

.github/workflows/chromatic.yml
- stories 파일이 없을 경우에도 Chromatic workflow가 실행 → 큰 의미는 없지만 결과적으로 ❌(실패는 아닌데 실패로..)
- paths로 `**.stories.tsx`가 존재할 경우에만 workflow가 실행되도록 설정했습니다.
(해당 PR 하단) 잘 적용된 거 확인했슴다 🕺
=> chore: stories 파일이 있을 경우에만 workflow 실행되도록

src/components/molecules/contentWrapper/ContentWrapper.stories.tsx, src/components/molecules/contentWrapper/ContentWrapper.tsx, src/components/molecules/contentWrapper/index.ts, src/components/molecules/index.ts
- 온보딩 및 홈화면에서 자주 사용되는 레이아웃 존재
- title, description(optional), children으로 구성하여 모듈화했어요.
- MVP 단계에서는 모든 title의 컬러가 동일하여 우선은 기본으로 `blue-50`으로 지정해 두었어요.
- 얼른 반영해서 준영넴과 같이 사용하면 좋을 거 같아서 빨리 PR 날렸슴다 🕺
=> feat: ContentWrapper 컴포넌트 및 Story 추가

src/components/atoms/bottomSheet/BottomSheet.stories.tsx, src/components/atoms/button/Button.stories.tsx, src/components/atoms/button/Button.tsx, src/features/auth/components/GoogleLoginButton.tsx, src/features/goal/components/new/GoalForm.tsx
- 기존에 모듈화 되어있던 Button 컴포넌트에 디자인 시스템 적용이 필요했습니다.
- [Figma 디자인 시스템](https://www.figma.com/file/hREAodauJnxgE6SBuF0ZYR/UI%2FDesgin-system?type=design&node-id=31-3667&mode=design&t=VcdFoMhuopQqbcUd-11) 참고하여 최대한 반영했습니다.
- variant: heavy, blue, tertiary, issue 입니다.
- icon이랑 함께 사용할 수 있도록 적용했습니다.
- 필요시 className으로 마음껏 스타일 변경 가능합니다 ^_^
- `blue`, `tertiary`, `issue`의 경우 hover 되었을 때 color를 10씩 올리려고 했으나 UX에 좋지 못한 것 같아서 우선 제외했습니다.
- 그래서 위 버튼들은 아직 많이 사용되지 않는 것 같아서, 추후에 디자이너분들께 hover시 bgColor와 textColor를 명시해 달라고 부탁드리면 좋을 거 같습니다.
- 디자인 시스템에서와 실제 UI에서의 disabled 스타일이 다른데... 우선 기존 Button의 disabled 스타일링으로 유지해놓았습니다(그랬더니 실제 UI에서 사용되는 스타일과 비슷한 거 같아요)
=> chore: atom/Button에 디자인 시스템 적용

next.config.js
- 홈 서버에 위치한  이미지를 읽기 위한 설정 추가
- next.config.js 설정 추가
- 설정 적용 후 출력 결과
사용 방법은 `import Image from 'next/image';` 를 사용하여 `src` 값에 서버의 asset url 그대로 넣어주시면 반영됩니다~
=> chore: 서버에 위치한 이미지 읽을 때 필요한 설정 추가

src/features/goal/components/new/DateForm.tsx, src/features/goal/components/new/FormHeader.tsx, src/features/goal/components/new/FormLayout.tsx, src/features/goal/components/new/GoalForm.tsx, src/features/goal/components/new/MoreForm.tsx, src/features/goal/components/new/StickerForm.tsx, src/features/goal/components/new/TagForm.tsx, src/features/goal/constants/goal.ts, src/features/goal/constants/index.ts
- 목표 추가 로직에 해당하는 페이지들의 미구현된 header를 구현하고 적용
- 홍석님이 목표 저장 페이지에 사용한 icon 재사용
- 프로그레스바는 두개의 div를 absolute를 이용하여 겹쳐 구현
- N/A
=> feat: 목표 추가 로직에 해당하는 페이지들의 header 구현 및 적용

.vscode/settings.json, src/app/goal/new/layout.tsx, src/features/goal/components/new/GoalForm.tsx, src/features/goal/components/new/StickerForm.tsx, src/features/goal/components/new/TagForm.tsx
- goal 추가 화면의 tag 추가 기능 구현
- react-query 반영된 sticker로 동작하는 스티커 추가 화면입니다.
https://github.com/depromeet/amazing3-fe/assets/34956359/fddd3bdb-4f38-458b-b056-ec25708a2aaa
** 추가로 해결된 내용:
- [] goal 추가 화면에 생기는 스크롤 문제 해결 (overflow-hidden 설정 반영했습니다)
- [] 세부 버튼 사이즈를 글자수에 맞게 조정
=> feat: goal 추가 화면의 sticker 추가 기능 구현

next.config.js, src/apis/httpClient.ts, src/app/globals.css, src/app/home/page.tsx, src/app/login/oauth2/code/google/page.tsx, src/features/customErrors/components/errorPageLayout/ErrorPageLayout.tsx, src/features/goal/components/detail/DeleteGoalButtomSheet.tsx, src/features/goal/components/detail/DetailFooterButton.tsx, src/features/goal/components/detail/DetailLayout.tsx, src/features/goal/components/detail/GoalDetailContent.tsx, src/features/goal/components/new/MoreForm.tsx, src/features/goal/components/new/StickerForm.tsx, src/features/home/components/lifeMap/LifeMap.tsx, src/features/member/types/form.ts, src/features/onboarding/components/onboardingBody/OnboardingBody.tsx, src/hooks/useDownloadImage.ts, src/middleware.ts
-  [사용자의 로그인 후 계정 생성 과정에 대한 버그 수정](https://github.com/depromeet/amazing3-fe/pull/56/commits/f64f7d0115f4bdeb978a8b41f8978c9fad8250ca)
- [홈, 목표 추가, 상세 확인 페이지 버그 수정](https://github.com/depromeet/amazing3-fe/pull/56/commits/0f0f123da9b97490b665e982a9969b32f22eeb95)
- oauth 성공 후 계정 정보가 없을 시 onboading 페이지로 이동하도록 경로 수정
- nickname로 이동하는 link가 버튼이 아닌 text에 적용된 부분 -> 버튼으로 변경
- 이미지 출력이 오래걸리는 문제 -> priority 적용으로 해결
- home 다운로드 시 파일 이름 변경
- pretendard font 반영 안되는 문제 해결
- 404, 500 이미지 preloading으로 변경
- db에서 가져오는 sticker 이미지 preloading으로 변경
- 공통 컴포넌트 사용으로 인해 버튼 디자인 깨지는 문제 수정
- cache에 반영 안된 라이브러리 추가
- home 화면에 적용한 hydration에서 오류를 유발하는 코드 일단 제거
- 에러 처리 로직 보강 및 개발 환경 시 바이페스할 수 있는 로직 추가
- redirection에 따른 alert 삭제
- 사용자 image 출력으로 변경
- N/A
=> bug: 배포 전 버그 수정 (온보딩, 에러 페이지, 홈, 목표 추가, 상세 페이지)

src/features/home/components/lifeMap/LifeMap.tsx
- 닉네임이 없는 경우 화면 레이아웃이 위로 쏠리는 이슈 있었습니다.
- 임시입니다... br 태그로 추가했습니다... 추후에 스타일로 수정하겠습니다 ㅠ
- N/A
=> bug: 홈화면에서 닉네임 없을 경우 레이아웃에 br 추가 (임시)

.pnp.cjs, package.json, src/hooks/useDownloadImage.ts, src/utils/image.ts, src/utils/userAgent.ts, yarn.lock
- ios / safari / firefox 에서 다운로드한 이미지가 제대로 출력되지 않는 이슈가 있었어요
- 텍스트 누락 / 스티커 이미지 누락
| <img src="https://github.com/depromeet/amazing3-fe/assets/80238096/ddec10ee-25b5-40b8-b56d-748c7cab2539" width="200px" /> | <img src="https://github.com/depromeet/amazing3-fe/assets/80238096/2b2cd38d-5442-4b41-b186-29c32d9b687d" width="200px" /> |
- img가 로드되기 전 + decode되기 전에 DOM을 이미지로 변환하기 때문에 발생한 버그
- html을 이미지로 변환하는 라이브러리인 html-to-image에 ios 이미지가 제대로 다운되지 않는 이슈가 있었어요
- https://github.com/bubkoo/html-to-image/issues/361
- 위 버그를 수정한 modern-screenshot 으로 이미지 다운로드 라이브러리 변경
- 모바일 사용자 경험을 위해 공유 기능으로 수정
| <img src="https://github.com/depromeet/amazing3-fe/assets/80238096/44916038-0052-49af-addf-8fd541632156" width="200px" /> | <img …
=> fix: ios에서 이미지 다운로드가 제대로 되지 않는 버그 해결

src/hooks/useDownloadImage.ts
- 다운로드 이미지 상단에 여백 추가
- 다운로드 되는 이미지 상단에 여백 추가
- 프리뷰에서는 여백이 제대로 나오는데 배포하니까 여백이 안보이는 이슈가 있어서 우선 paddingTop 추가했습니다!
- 프리뷰 때 다운로드 되는 이미지랑 배포에서 다운로드 되는 이미지랑 여백이 달라서 테스트가 어렵네요🥹
=> fix: 다운로드 이미지 상단에 여백 추가

src/features/goal/components/new/StickerForm.tsx, src/features/goal/components/new/TagForm.tsx
- [tag, sticker 돌아오면 선택 안되어 있는 문제 해결](https://www.notion.so/depromeet/tag-sticker-27cb63aef63a4fd4b2f5fe55d38bc7d6?pvs=4) 
- getValues 값을 통해 해당하는 값이 지정되어 있으면 반영하도록 수정
https://github.com/depromeet/amazing3-fe/assets/34956359/9a74063e-d5af-45f9-9e17-b4d8065f31db
=> bug: tag, sticker 돌아오면 선택 안되어 있는 문제 해결

src/app/layout.tsx, src/app/onboarding/layout.tsx, src/constants/metadata.ts, src/features/onboarding/components/onboardingBody/OnboardingBody.tsx, src/hooks/reactQuery/auth/useCreateMemberData.ts, src/hooks/reactQuery/auth/useGetMemberData.ts
- 1) onboarding 페이지가 SEO에 등록되면서 의미있는 정보를 제공하려고 내용에 변화를 주었습니다.
- 2) onboarding에서 사용자의 상태에 따라 시작하기 버튼 동작을 다르게 지정하여 해당 페이지로 직접 들어와도 사용자 경로에 문제가 생기지 않도록 수정했습니다.
- 3) 처음 nickname 등록 후 /home 화면에 username이 출력되지 않는 문제를 해결했습니다.
1) metadata 정보 추가
2) react-query의 [enabled 옵션](https://tanstack.com/query/v4/docs/react/guides/disabling-queries)을 사용하여 아래의 문제를 해결했습니다.
조건 | AS-IS | TO-BE |
|----|----|----|
| accessToken 없이 onboarding 화면 접속 | 401 에러로 즉시 '/' 경로로 이동 | `시작하기` 버튼 클릭 전까지 onboarding 페이지 출력 |
| nickname이 있는 사용자가 유효한 토큰이 있는 상태에서 onboarding 화면 접속 | nickname 설정하는 화면으로 이동 | `home`으로 이동 |
3) invalidateQueries 설정으로 home에서 사용자 정보 조회 시 반영된 nickname 출력 가능하도록 설정.
https://github.com/depromeet/amazing3-fe/assets/34956359/f65c83e5-27d5-4111-bb1a-536186eb5fe3
=> bug: 사용자 상태에 따른 onboarding 시작하기 기능 분리 및 metadata 수정

src/features/member/components/new/BirthInputForm.tsx
- 첫 가입시 생년월일을 입력할 때, 새로고침 등으로 입력한 nickname이 초기화되어 `undefined`로 나타나는 현상
- 생년월일 입력 페이지에서 `react-hook-form`에 등록된 닉네임이 없을 경우, 닉네임 입력 페이지로 라우팅
- 해당 방법 말고 더 나은 방법이 있을까요.. 😢 아무리 생각해도 저는 이것 밖에..
- 추후 이미 온보딩 과정을 거친 유저에 대해서는 온보딩 과정 페이지에 접근할 수 없도록 하는 과정이 필요할 것 같아요
=> bug: 생년월일 입력시 닉네임이 undefined로 보이는 현상

src/contexts/reactQuery/QueryClientProvider.tsx, src/hooks/reactQuery/goal/useDeleteGoal.ts, src/hooks/reactQuery/goal/useGetGoals.ts
- [react-query 적용 이슈 (hydtration, invalidateQueries)](https://www.notion.so/depromeet/react-query-hydtration-invalidateQueries-02589dccff924b76affedba7f19ee1e4) 중 invalidQueries 적용 이슈
- `refetchOnMount: false` 옵션으로 인해 마운트 시 refetch가 되지 못해 invalidQueries가 적용되지 못한 걸로 파악되었습니다.
- 이럴 경우 stateTime을 주어야 일반적인 mount 시에는 refetch를 하지 않습니다!
- 저희 서비스 현재 단계 기준으로, 적절한(?) staleTime은 `Infinity`라고 생각이 들어 모든 query에 `staleTime: Infinity` 적용해 주었습니다.
- 항상 staleTime과 gcTime(구 cacheTime)에 대한 고민이 가장 알쏭달쏭한데.... 더 좋은 의견 있으시면 무한 감사드리겠습니다 많관부..
=> bug: invalidQueries 적용 이슈 해결

src/features/home/components/mapSwiper/MapSwiper.tsx
- initialSlide가 추가되고 나서 현재 시간이 첫 페이지에 있다면 페이지 값이 0 (false)로 처리되는 문제 발견.
- 명시적으로 null 값인지 확인하는 로직으로 변경
- 목표가 4개 이상 없는 사용자는 목표를 볼 수 없습니다ㅠ0ㅠ  긴급긴급ㅠㅡㅠ
=> bug: initialSlide가 0인 경우 Swiper가 출력되지 않는 이슈

src/features/home/components/MapCardCollections/MapCard/MapCard.stories.tsx, src/features/home/components/MapCardCollections/MapCard/MapCard.tsx, src/features/home/components/MapCardCollections/MapCardLayout.tsx
위 이미지처럼 텍스트 길이가 조금 길어질 경우 레이아웃 이슈 발견했습니다.
- 전체를 flex로 하여 가운데로 조정하는 방식으로 변경
- 상하좌우 padding으로 5px만을 주어, 최소한의 공백 적용
적용된 후 입니다 ^_^ㅠ
=> bug: MapCard 레이아웃 이슈 해결

src/app/layout.tsx, src/features/analyzer/GoogleAnalytics.tsx, src/features/analyzer/index.ts
- [Google Analytics 적용](https://www.notion.so/depromeet/Google-Analytics-d56a2ec36baf4a1b84b66478c39da054?pvs=4)
- [Next 공식 문서](https://nextjs.org/docs/messages/next-script-for-ga)를 활용
- 우선 vercel에 GA 측정 ID를 환경 변수에 추가해뒀습니다
- 보통 `hotjar`와 `mixpanel`을 분석 툴로 많이 사용한다고 하는데, 모바일 환경을 고려한다면 `mixpanel`이 유저 행동과 이벤트를 중점적으로 분석해줘서 좋다고 하네요!
- [Reference](https://www.fullsession.io/blog/hotjar-vs-mixpanel-vs-clicktale/)
- 그래서 `mixpanel`도 같이 붙여볼까 고려중이였는데 오버엔지니어링이라는 생각이 들긴하네요
- 그리고 이벤트를 다루는 모든 함수에 로깅 함수를 달아줘야하는 것 같긴 합니다 ㅠ
- 혹시나 <ins>더 좋은 아이디어나 필요하다고 생각되는 기능</ins>이 있으면 말씀해주세요!
=> chore: Google Analytics 추가

next.config.js, src/app/layout.tsx, src/constants/metadata.ts
네이버 로그인과 관련된 설정을 추가했습니다.
- Naver 로그인 후 프로파일 이미지 출력 시 필요한 설정 추가
- naver 검색을 통해 들어올 사용자를 위한 NAVER SEO 추가
- 불필요한 환경 변수 제거
- 해당 값은 head tag에 그대로 출력되고 있기에 불필요하게 환경 변수로 관리할 필요가 없어 제거했습니다.
- 로그인을 위한 버튼은 도은 선생께서 작업하신 게 있어 dev에서 합친 후 테스트 해보겠습니다~
=> bug: OAuth 이미지를 출력하기 위한 설정 추가

src/hooks/useDownloadImage.ts
- 이미지 다운로드시, 전체 인생지도가 다운로드가 될 수 있도록 변경했어요
| <img src="https://github.com/depromeet/amazing3-fe/assets/80238096/efbe2d99-cc7a-4e03-a93e-226db5d2ebdb" width="200px" /> |<img src="https://github.com/depromeet/amazing3-fe/assets/80238096/8d978a8e-0e3d-42b1-b114-a093fbf59b4d" width="300px" /> |
| 한 페이지씩 다운로드 | 전체 페이지 다운로드 | 
이미지 다운로드 라이브러리의 `onCloneNode` 옵션을 사용해서 클론된 html의 스타일을 변경하는 방식을 사용했어요
> 현재 사용중인 이미지 다운로드 라이브러리는 html을 클론 후 -> 이미지로 변경(html-to-image)하는 방식을 사용해요
- 이미지 다운로드 시, 기존 swiper에 적용되어있는 `overflow:hidden` 속성을 `visible`로 변경해서 전체 인생지도가 보일 수 있도록 했어요
- 어떤 페이지에서 다운로드해도 전체 인생지도가 다운로드될 수 있도록 `translate3d` 속성을 수정했어요
- 다운로드될 이미지의 넓이를 구하기 위해 goals의 개수를 통해 계산했어요
- 코드.. 굉장히 마음에 안드는데요.. 
- 이미지 다운로드를 하는데 goals의 개수를 알아야하는 점.. 강결합이 미쳤네요..
- querySelector로 요소 가져와서 …
=> feat: 현재 페이지 이미지 다운로드 -> 전체 페이지 이미지 다운로드로 변경

src/app/page.tsx, src/constants/externalURL.ts
- 카카오 Oauth 검수 과정에서 필요한 개인정보 처리 방침 링크 적용 
- a tag 적용하여 반영 (보안을 위해 noopener noreferrer 속성값 적용)
- notion 링크 공개를 위한 커스텀 도메인 변경 (`mammoth-smell-342.notion.site` -> `bandiboodi.notion.site`)
- 서비스 이용약관도 해야하는데... 일단 검수 결과 나오는 거 보고 서비스 이용약관 때문에 반려당하면 따로 만들어서 넣을게요 흑흑
=> docs: 개인정보 처리 방침 문서 외부 링크 적용

src/components/atoms/toast/Toast.tsx, src/components/atoms/toast/ToastProvider.tsx, src/contexts/Providers.tsx, src/features/goal/components/detail/task/Task.tsx, src/features/goal/components/detail/task/TaskEditInput.tsx
- 모바일에서 Toast의 메시지가 짧음에도 줄바꿈이 되는 이슈
- 모바일에서 세부목표 수정 input의 border-bottom 스타일 이슈
- Toast가 떠있는 시간이 조금 길다고 느껴짐 (개인적으로..
| Toast 이상 | Input 이상 |
|:--:|:--:|
| ![IMG_7903](https://github.com/depromeet/amazing3-fe/assets/112946860/9d804a16-c24b-4182-9506-5650ef4be6e5) | ![IMG_7904](https://github.com/depromeet/amazing3-fe/assets/112946860/2dff2586-c00c-4201-95ca-a37e16fa8384) |
- 스타일 수정..수정...
https://github.com/depromeet/amazing3-fe/assets/112946860/4b309d38-3baa-42a7-862a-8039eaa8f2b5
=> bug: 세부목표 페이지 세부 스타일 이슈 해결

src/app/onboarding/layout.tsx, src/features/onboarding/components/onboardingBody/OnboardingBody.tsx, src/features/onboarding/components/onboardingLayout/onboardingLayout.tsx, src/features/onboarding/components/onboardingSwiper/OnboardingSwiper.tsx
- safari(모바일)에서 온보딩 페이지 레이아웃 이슈
- 스타일 일부 수정했습니다.....~~
| safari | chrome |
|:--:|:--:|
| <img width="229" alt="image" src="https://github.com/depromeet/amazing3-fe/assets/112946860/f591c913-361b-44bf-a211-cc4802898987"> | <img width="229" alt="image" src="https://github.com/depromeet/amazing3-fe/assets/112946860/62e0be03-9d7e-48f7-82e4-80c1b69e0dfe"> | 
사파리는...죽어도 padding-bottom이 안 들어가긴 해서 그나마 이쁘게 보이는 걸로 마무리합니다...~~~!
- N/A
=> bug: 온보딩 페이지 레이아웃 이슈 해결

src/app/goal/detail/saved/page.tsx, src/app/oauth2/token/page.tsx, src/features/goal/components/detail/DeleteGoalBottomSheet.tsx, src/features/goal/components/detail/DeleteGoalButtomSheet.tsx, src/features/goal/components/detail/DetailHeader.tsx, src/features/goal/components/detail/SavedFooterButton.tsx, src/features/goal/components/detail/SavedHeader.tsx, src/features/home/components/lifeMap/LifeMapContent.tsx, src/features/home/components/mapSwiper/MapSwiper.tsx, src/features/member/contexts/NewMemberFormProvider.tsx, src/hooks/reactQuery/goal/useDeleteGoal.ts, src/hooks/reactQuery/goal/useGetGoals.ts
[Goal 신규 생성 및 Goal Detail 조회 후 홈 화면 이동 시 해당 위치로 point 잡기](https://www.notion.so/depromeet/Goal-Goal-Detail-point-f2ab0c04d02241f8b46e8f29a60946e8?pvs=4)
- 목표 생성 시 생성된 목표 스라이드로 이동 (prefetch 적용)
- 목표 상세 페이지 접근 후 뒤로 가기 수행 시, 같은 슬라이드로 이동
- 목표 상세 페이지에서 목표 삭제 수행 시, 현재 시간 스라이드로 이동
https://github.com/depromeet/amazing3-fe/assets/34956359/50c3ca81-8b8d-4a93-bea1-2e3e8810a894
- N/A
=> feat: 목표 생성, 목표 상세보기, 목표 삭제 후 현재 페이지 변경 로직 추가

src/hooks/useDownloadImage.ts
- ios에서 이미지 다운로드 안되는 이슈 해결
- ios에서 이미지 다운로드 시 공유 기능 -> 파일 다운로드로 수정
https://github.com/depromeet/amazing3-fe/assets/80238096/7993847c-aed0-41dc-b6fe-8e381d4eb59f
=> fix: ios에서 인생지도 다운로드 안되는 이슈 해결

src/features/home/components/MapCardCollections/MapCard/MapCard.tsx, src/features/home/components/lifeMap/LifeMapContent.tsx, src/features/home/components/lifeMap/PublicLifeMap.tsx, src/features/home/components/loginBottomSheet/LoginBottomSheet.tsx, src/features/my/components/logoutBottomSheet/Footer.tsx
- [로그인 시 남의 목표 카드 클릭 시 로그인 bottom sheet 출력](https://www.notion.so/depromeet/bottom-sheet-1b9f8e10c130438a99ffa29dcced60f0?pvs=4)
- [남의 홈 화면에서 내 홈으로 가는 버튼 필요](https://www.notion.so/depromeet/9c0441b9ab2844269899d4e5638a8112?pvs=4)
- 지도 클릭 시 클릭 이벤트 추가 (로그인 안했을 때 로그인 bottom sheet 띄우기)
- public 지도 접근 시 하단에 `내 지도로 돌아가기` 버튼 생성
- 로그아웃 시 isLoginAtom 값 false로 변경
https://github.com/depromeet/amazing3-fe/assets/34956359/594bb9bc-f7c9-4704-923d-5d8e0c869fad
- 남의 목표 상세보기 화면에서 상세목표 등록하기, 완료표시 등 수정 기능 사용 못하도록 수정 필요 (https://www.notion.so/depromeet/9de0c9b05d1c49d998844728eae0e166?pvs=4)
=> feat: 로그인 안한 사용자가 상세 목표 조회 시 로그인 버튼 시트 출력

src/components/atoms/toast/Toast.tsx, src/features/member/components/new/NicknameInputForm.tsx, src/features/member/contexts/NewMemberFormProvider.tsx, src/features/member/types/form.ts, src/features/my/components/update/ProfileImageBottomSheet.tsx, src/features/my/components/update/ProfileImageButton.tsx, src/features/my/components/update/UpdateForm.tsx, src/features/my/components/withdrawBottomSheet/Footer.tsx, src/features/my/contexts/UpdateMemberDataFormProvider.tsx, src/features/my/types/form.ts, src/hooks/reactQuery/auth/index.ts, src/hooks/reactQuery/auth/useCreateMemberData.ts, src/hooks/reactQuery/auth/useDeleteMemberData.ts, src/hooks/reactQuery/auth/useUpdateMemberData.ts, src/hooks/reactQuery/profile/index.ts, src/hooks/reactQuery/profile/useGetDefaultProfileImages.ts
- [마이페이지 수정 기능 온보딩과 분리 필요 + 프로파일 이미지 선택 필드 추가](https://www.notion.so/depromeet/8a67704e442c43fba76710e1ac549515?pvs=4)
- 기존 put /my 로직을 api에 맞게 수정
- 온보딩 테스트를 위해 dev인 경우 사용할 수 있는 탈퇴 기능 개발
- profile image를 포함한 put /users api 적용
- get /profile/default api를 통해 가져온 프로파일 이미지를 bottom sheet에 출력하고, 이미지 하나 선택 시 프로파일에 보여주도록 기능 개발.
- update 수행 시 409 에러 발생 시 중복된 username이 존재한다는 메세지 toast로 출력
- toast 출력 시간이 너무 짧아 조금 늘림.
https://github.com/depromeet/amazing3-fe/assets/34956359/4edc331d-9c4d-45a1-9f0b-e1ed41f541ba
- TODO: update 수행하는 동안 '저장' 버튼 disable 시킬 방법 찾기
=> feat: 마이페이지 수정 기능 반영과 관련 프로파일 이미지 선택 필드 추가

src/features/member/components/new/BirthInputForm.tsx, src/features/my/components/update/UpdateForm.tsx, src/hooks/useValidBirth.ts
- [현재 날짜보다 미래의 날짜로 생년월일 설정이 가능](https://www.notion.so/depromeet/a8b9082115d44200b0d0a3307aac2394)
- 오늘 날짜를 기준으로 미래를 입력했을 경우, 버튼 disbaled 처리 및 toast 알림
https://github.com/depromeet/amazing3-fe/assets/112946860/015e7bd8-a0bc-471c-8e04-94af5b26d957
https://github.com/depromeet/amazing3-fe/assets/112946860/5a2fec70-77c7-4284-96d5-88856b8317a0
=> bug: 생년월일로 미래를 입력할 경우 disabled & toast 처리

src/features/my/contexts/UpdateMemberDataFormProvider.tsx, src/hooks/reactQuery/auth/useUpdateMemberData.ts
- 사용자 정보 업데이트 시, 로컬스토리지도 업데이트 되도록 수정
- 사용자 정보 업데이트 시, 로컬스토리지도 업데이트 되도록 수정
-
=> fix: 사용자 정보 업데이트 시, 로컬스토리지도 업데이트 되도록 수정

src/constants/storageKey.ts, src/features/goal/components/detail/DetailHeader.tsx, src/features/goal/components/detail/GoalDetailContent.tsx, src/features/goal/components/detail/Tasks.tsx, src/features/goal/components/detail/task/Task.tsx, src/features/home/components/lifeMap/LifeMap.tsx, src/hooks/index.ts, src/hooks/useIsMyMap.ts
- [로그인한 사용자가 남의 목표 상세를 변경할 수 있는 문제 해결 (뒤로 가기 시 내 지도로 돌아가는 문제도 해결)](https://www.notion.so/depromeet/9de0c9b05d1c49d998844728eae0e166)
- 세부목표 화면에서 `x` 아이콘 클릭 시 **현재 보고 있던 인생지도로** 갈 수 있도록
- 다른 사람 세부목표일 경우, `수정/삭제/목표달성` 버튼 **비활성화 및 보이지 않도록** 
https://github.com/depromeet/amazing3-fe/assets/112946860/5e42db9d-011f-490d-a355-56efd251abd8
=> bug: 내 지도인지 아닌지에 따라 세부목표 화면 일부 수정

src/features/goal/components/new/TagForm.tsx
- [태그 선택 페이지 레이아웃 이슈](https://www.notion.so/depromeet/470491e28c4a4230a0847ad81d188024)
- 스타일 일부 수정
|:--:|:--:|
| <video src="https://github.com/depromeet/amazing3-fe/assets/112946860/8f9ee774-9369-4f5d-8108-faaaaeb81bf9" /> | <video src="https://github.com/depromeet/amazing3-fe/assets/112946860/ac7b837b-f186-4fc1-bcf4-e070bf7b54f7" /> |
=> bug: 태그 폼 레이아웃 이슈 해결

src/features/goal/components/detail/DeleteGoalBottomSheet.tsx
- [[목표 삭제] 버튼 간격 스타일, UX라이팅, 반디부디 크기 조정](https://www.notion.so/depromeet/UX-ce8039d124b941898b867cd07d1da218)
- nickname 표시
- 반디부디 이미지 크기 축소
- 스타일 일부 수정
|:--:|:--:|
| ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/31f8cef3-8c79-4abf-a50f-bb285f6c32d3) | ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/6e1186f3-61a0-43a3-b420-adccd4ce7029) |
=> chore: 목표 삭제 바텀시트에 nickname 표시 및 스타일 수정

src/components/atoms/toolTip/ToolTip.tsx, src/features/goal/components/detail/SavedFooterButton.tsx, src/features/goal/components/detail/SavedHeader.tsx, src/features/goal/components/new/GoalForm.tsx, src/features/goal/components/new/MoreForm.tsx, src/features/goal/components/new/TextInput.tsx
- [목표 작성 메모 입력 step](https://www.notion.so/depromeet/step-8bba5f2bcbaf4433b54361b7769fd25c)
- 메모 입력 필드 글자 수 카운트 되도록 반영
- 메모 입력 필드 height를 vh로 지정하여 버튼과 최대한 겹치지 않도록 스타일 적용
- 목표 저장 시 상단 `>` 버튼 제거
- 목표 저장 시 하단에 ToolTip 추가
| `>` 버튼 제거 및 ToolTip 추가 | 메모 입력 필드 글자수 카운트 및 레이아웃 수정 |
|:--:|:--:|
| <img src="https://github.com/depromeet/amazing3-fe/assets/112946860/71973969-4fc4-4535-a161-cd572a32fc3e" width="600" />| ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/01cdf83a-c5f8-4ff7-8f19-005c2a38c41a) |
=> bug: 세부목표 추가 스텝 부분 이슈 및 빠진 부분 추가

src/features/home/components/MapCardCollections/EmptyMapCard/EmptyMapCard.tsx
=> bug: 빈 목표 카드 선택 시 목표 생성 화면으로 redirection

src/features/goal/components/new/TagForm.tsx
- 태그 선택 시, 버튼이 안눌리는 이슈 해결
- 태그 영역의 높이에 버튼 일부가 겹쳐서 안눌리는 현상 해결
-
=> fix: 태그 선택 시, 버튼이 안눌리는 이슈 해결

src/features/home/components/MapCardCollections/EmptyMapCard/EmptyMapCard.tsx
- 빈 카드 선택 시 goal 생성 화면으로 이동하는데 남의 지도에서는 그게 조금 이상함.
- 로그인한 사용자가 본인의 지도에서 빈 목표 클릭 시, 목표 생성 화면으로 이동.
- 로그인한 사용자가 남의 지도에서 빈 목표 클릭 시, 아무 동작 안함.
- 로그인하지 않은 사용자가 남의 지도에서 빈 목표 클릭 시, 로그인 버틈 시트 출력.
-
=> bug: 남의 지도에서 빈 목표 카드 선택 시 사용자 상태에 따른 로직 분리

src/features/home/components/MapCardCollections/MapCardLayout.tsx
- ios safari에서 box-shadow가 제대로 렌더링 되지 않는 이슈를 해결했습니다
- 관련 이슈: https://github.com/niklasvh/html2canvas/issues/1856 
- 이슈가 발생하는 요소에 box-shadow 제거
https://github.com/depromeet/amazing3-fe/assets/80238096/3c947a3f-f5fa-48d8-ba8d-218e518afb29
-
=> fix: 목표 조각에 box shadow 제거

src/features/home/components/lifeMap/LifeMapInfo.tsx, src/hooks/reactQuery/goal/useGetGoals.ts
- 응원하기 개수 고정 값 -> api 응답 값으로 수정
- `/life-map` 응답 값에 추가된 `count` 값을 사용
=> feat: 응원하기 개수 api 응답 값으로 수정

src/app/page.tsx
- 에브리타임으로 홍보 해서 인앱 브라우저로 들어갔는데, 다크모드에서 이래 보이네용
아래 표시한 부분이 조금 짧은 거 같아서 살짝만 늘렸어요~~!
- N/A
=> bug: 스플래시 화면에서 뒷 배경 길이 조절

src/features/my/components/MyPageLayout.tsx, src/features/my/components/MyPageLifeMapInfo.tsx, src/hooks/reactQuery/cheering/index.ts, src/hooks/reactQuery/cheering/useGetCheeringCount.ts
- 응원하기 개수 조회 api 연동
- 조회수 조회 api는 별도로 없고, `/life-map` 조회할 때만 있어서 추후 서버에 작업 요청 예정입니다 
-
=> feat: 응원하기 개수 조회 api 연동

src/features/goal/components/detail/Tasks.tsx, src/features/goal/components/detail/task/Task.tsx, src/hooks/index.ts, src/hooks/reactQuery/task/useUpdateIsDone.ts, src/hooks/useDebounceCall.ts
- https://github.com/depromeet/amazing3-fe/pull/107 에서 언급했던 체크박스가 **일정시간 유지되면 그때 요청**보내는 기능 추가
- debounce로 클릭할 때마다 요청 보내는 것이 아니라, 0.5초 유지 시에만 요청 보내도록 했습니다.
- 낙관적 업데이트하던 코드는 제거했습니다.
=> refactor: 세부목표 isDone 요청에 debounce 추가

src/constants/index.ts, src/constants/time.ts, src/features/home/components/lifeMap/PublicLifeMap.tsx, src/hooks/index.ts, src/hooks/reactQuery/cheering/useCreateCheering.ts, src/hooks/useThrottle.ts
- 1분에 한 번만 응원하기 누를 수 있도록 구현
- useThrottle 훅 추가
https://github.com/depromeet/amazing3-fe/assets/80238096/cb0379d1-45ed-47f6-a1d7-d8f21e981acf
-
=> feat: 1분에 한 번만 응원하기 누를 수 있도록 구현

src/features/my/contexts/UpdateMemberDataFormProvider.tsx
- 사용자가 username 변경 시 `BANDIBOODI-`로 시작하는 이름으로 설정하면 이후 신규 유저 등록 과정에서 오류가 발생할 가능성이 있음.
- form submit 시 username 체크 로직 추가. -> `BANDIBOODI-`로 시작하는 이름으로 설정했을 때 토스트로 알림.
참고:
- 현재 Input atom의 커버리지가 지나치게 사용되고 있어 용례에 따라 구분할 필요가 있어보입니다.
- 따라서, error 상태를 따로 추가하기 보다는 나중에 validation을 수행하는 input atom을 별도로 만들어서 처리하겠습니다.
https://github.com/depromeet/amazing3-fe/assets/34956359/b6c27edd-a6e0-43a3-961e-c31e0abaea4c
=> bug: username에 BANDIBOODI가 포함된 경우 validation 실패 처리

src/features/home/components/lifeMap/PublicLifeMap.tsx, src/features/my/contexts/UpdateMemberDataFormProvider.tsx
- 이슈 1: username이 없는 경우에 응원하기 불가하도록 수정
- 이슈 2: username 수정 시 영문, 숫자, - 만 사용 가능하고, 시작과 끝은 - 가 들어갈 수 없음.
- 이슈 1: username이 없는 경우에 응원하기 불가하도록 수정
https://github.com/depromeet/amazing3-fe/assets/34956359/7758a7c4-7e14-4c08-95bf-f0f19a41076f
- 이슈 2: username 수정 시 영문, 숫자, - 만 사용 가능하고, 시작과 끝은 - 가 들어갈 수 없음.
https://github.com/depromeet/amazing3-fe/assets/34956359/663ebcb7-3a2e-4c1f-99ac-2a82f077526f
-
=> Bug: username 수정 제한 설정 및 응원하기 수행 조건 추가

.pnp.cjs, next.config.js, package.json, sentry.client.config.ts, sentry.edge.config.ts, sentry.server.config.ts, src/app/global-error.tsx, src/components/atoms/lottie/Lottie.tsx, src/hooks/useDownloadImage.ts, yarn.lock
- 번들 사이즈 축소
- [bundle-analyzer](https://nextjs.org/docs/app/building-your-application/optimizing/bundle-analyzer)를 이용해서 측정
- 측정 결과, lottie 번들 사이즈가 `299kb`로 측정
- `lottie_light.min.js`에서 모듈을 불러옴
- lottie-light는 svg 렌더링만 지원함 
- [관련 이슈 참고](https://github.com/airbnb/lottie-web/issues/1184#issuecomment-411585735)
| ![image](https://github.com/depromeet/amazing3-fe/assets/80238096/1e03ce02-932a-410b-8871-b80427860c52) | ![image](https://github.com/depromeet/amazing3-fe/assets/80238096/27c05d23-c25e-4129-9605-393413128f50) |
| gzip `75kb` | gzip `44kb` | 
| ![image](https://github.com/depromeet/amazing3-fe/assets/80238096/17513ed2-a229-4b5f-b7ca-be79154ead4c) | ![image](https://github.com/depromeet/amazing3-fe/assets/80238 …
=> refactor: 번들 사이즈 개선

.pnp.cjs, next.config.js, package.json, sentry.client.config.ts, sentry.edge.config.ts, sentry.server.config.ts, src/app/fonts.ts, src/app/global-error.tsx, src/app/home/[username]/layout.tsx, src/components/atoms/lottie/Lottie.tsx, src/features/home/components/MapCardCollections/EmptyMapCard/EmptyMapCard.tsx, src/features/home/components/lifeMap/LifeMapContent.tsx, src/features/home/components/lifeMap/PrivateLifeMap.tsx, src/features/home/components/lifeMap/PrivateLifeMapBottomArea.tsx, src/features/home/components/lifeMap/PublicLifeMap.tsx, src/features/home/components/lifeMap/PublicLifeMapBottomArea.tsx, src/features/home/components/mapSwiper/MapSwiper.tsx, src/features/home/components/mapSwiper/index.ts, src/features/home/components/shareBottomSheet/index.ts, src/hooks/useDownloadImage.ts, styles/theme/backgroundImage.ts, yarn.lock
- 인생 지도 페이지 성능 개선
pagespeed
- [측정 결과 링크](https://pagespeed.web.dev/analysis/https-www-bandiboodi-com-home-newminkyung/11q1gs5exf?form_factor=mobile)
- 완전히 신뢰할 수 있는 지표는 아니지만 그래도 이건 좀 🚬
- 이거 돌려보고 살짝 충격받아서 간단한 작업만 진행해봤읍니다..
1. 불필요한 폰트 제거
- 일부 font-weight만 쓰고 있어서 불필요한 폰트는 제거
| ![image](https://github.com/depromeet/amazing3-fe/assets/80238096/4298028e-2a7d-4634-b26b-93fdce33150f) | ![image](https://github.com/depromeet/amazing3-fe/assets/80238096/1a4cba6f-8291-47ee-a3d7-cd456cb46dd2) |
| 9개 | 5개 | 
2. purple blur 이미지 -> css 속성으로 변경
- 지도 페이지에서 제일 큰 컨텐츠가 purple blur 이미지
- css gradient 속성으로 변경
3. dynamic import 적용
- 당장 보여야하는 컴포넌트를 제외하고는 dynamic import 적용
-  지도 하단 버튼 영역에 dynamic import 적용
4. edge runtime 적용
- node.js -> edge로 런타임 변경
- 이 부분은 얼마나 빨라질지 모르겠지만 우선 …
=> refactor: 인생지도 페이지 성능 개선

src/app/oauth2/token/page.tsx, src/features/goal/components/new/DateInput.tsx, src/features/member/components/new/BirthInputForm.tsx, src/features/member/contexts/NewMemberFormProvider.tsx, src/features/member/types/form.ts, src/features/my/components/update/UpdateForm.tsx, src/features/my/components/userProfile/UserProfile.tsx, src/features/my/types/form.ts, src/hooks/reactQuery/auth/useCreateMemberData.ts, src/hooks/useValidBirth.ts
- 앱 심사 반려로 인해  온보딩 생년월일 입력을 optional로 변경합니다
- [관련 스레드](https://depromeet14th.slack.com/archives/C0650S7UY5S/p1709768532315479)
- 생년월일 필드 optional로 변경
- 생년월일 입력하지 않을 시, 버튼 내용 `완료` -> `건너뛰기`로 수정
https://github.com/depromeet/amazing3-fe/assets/80238096/c0af5f8a-de18-4cb9-aa22-cbd2f50d5edc
=> feat: 온보딩 생년월일 입력 optional로 변경

src/features/my/components/update/UpdateForm.tsx
- 프로필 수정 시, birth가 null일 경우 발생하는 오류 수정
- 온보딩에 생년월일을 입력하지 않은 사용자가 > 프로필 수정을 눌렀을 때 > birth가 null이기 때문에 오류 발생
-> 옵셔널 체이닝으로 수정
- 테스트 방법
1. 온보딩에 생년월일 입력 x
2. 프로필 이미지 클릭 후 수정
=> fix: 프로필 수정 시, birth가 null일 경우 발생하는 오류 수정

sentry.client.config.ts, sentry.edge.config.ts, sentry.server.config.ts
- 프로덕션일때만 sentry 에러 캐치하도록 수정
- 프로덕션일때만 sentry 에러 캐치하도록 수정
-
=> chore: 프로덕션일때만 sentry 에러 캐치하도록 수정

src/components/molecules/infiniteScroll/InfiniteScroller.tsx, src/features/cheering/CheererList.tsx, src/hooks/useIntersectionObserver.ts, src/utils/generateId.ts
- 무한스크롤 한 번 스크롤 시 여러번 요청하는 버그 수정
- 한 번 스크롤 시, 한 페이지만 요청해야하는데 페이지 여러개를 호출하는 버그 수정
- Intersection Observer API 사용하는 커스텀 훅 수정 
- 키 값 중복 수정 
- 탈퇴한 유저인 경우, 모든 응답 값이 똑같아서 키 중복 발생 
- 고유한 아이디 값 생성하는 유틸 함수 추가
- 지능 떨어진채로 수정해서 제대로 동작 하지 않을 수도 .. 더 좋은 방법이 있을 수 있으니 많의부
=> fix: 무한스크롤 한 번 스크롤 시 페이지 여러개 요청하는 버그 수정

src/features/emoji/ReactionAddButton.tsx, src/features/feed/feedCard/FeedCard.tsx, src/features/feed/feedCard/FeedCardBody.tsx, src/features/feed/feedCard/FeedCardHeader.tsx, src/features/feed/feedCard/FeedCardLayout.tsx, src/features/feed/feedCard/ViewCommentButton.tsx, src/features/feed/feedCard/reactionGroup/Emojis.tsx, src/features/feed/feedCard/reactionGroup/ReactedEmojiButton.tsx, src/features/feed/feedCard/reactionGroup/ReactionGroup.tsx, src/features/feed/feedCard/reactionGroup/SelectReactionWindow.tsx, src/features/feed/feedCard/reactionGroup/index.ts
- 피드 페이지의 피드 카드 기능 연결 및 퍼블리싱
- 피드 카드별 퍼블리싱된 댓글 바텀 시트 연결 및 리액션 기능 퍼블리싱
- 피드 카드 리팩토링
- 아직 피드 API 에서 리액션쪽 구조가 안나와서 props가 아닌 테스트 데이터 형태로 집어넣어놨습니다 ㅠ
- 타임라인에서 재활용할 FeedCardLayout과 FeedCardBody를 molecule에 어떻게 넣을지 고민중..
- 나머지는 이제 앞으로 API 연결하면서 완성하면 끝일듯!
- 아 그리고 피드 페이지 무한 스크롤도 완료해서 적용만 하면 끝이라 민경센세 버그 수정 PR 들어가고 나서 PR 바로 올리겠슴다 🫡
=> feat: 피드 페이지 댓글 바텀 시트 연결 / 리액션 기능 퍼블리싱

src/features/emoji/BottomSheet/Content.tsx, src/features/emoji/BottomSheet/Header.tsx, src/features/emoji/BottomSheet/ReactUserBottomSheet.tsx
- 이모지 관련 컴포넌트 중 필요한 모듈만 import하도록 (`@radix-ui/react-tabs`)
- 필요한 모듈만 import
- N/A
=> refactor: 이모지 관련 컴포넌트 중 필요한 모듈만 import하도록

src/features/cheering/Cheerer.tsx
- 응원한 사람 프로필 이미지 높이 깨지는 현상 수정
- [관련 슬랙](https://depromeet14th.slack.com/archives/C064475K71C/p1710656693276839)
- 높이가 32px 보다 늘어나지 않도록 `max-height` 추가
| <img width="400" alt="스크린샷 2024-03-17 오후 3 48 16" src="https://github.com/depromeet/amazing3-fe/assets/80238096/ea60dd01-87cf-4c57-bbfa-1a8cc2903e08"> | <img width="520" alt="스크린샷 2024-03-17 오후 3 48 16" src="https://github.com/depromeet/amazing3-fe/assets/80238096/4a289c51-f9d0-44a6-b502-e5676c6dd851"> |
-
=> fix: 응원한 사람 프로필 이미지 높이 깨지는 현상 수정

src/features/home/components/lifeMap/LifeMapContent.tsx, src/features/home/components/lifeMap/PublicLifeMap.tsx
- 남의 지도에서 공유 버튼을 -> 프로필 이미지로 변경
https://github.com/depromeet/amazing3-fe/assets/80238096/76c3a712-f5f8-45cb-99d1-430b6ee5a8da
```
- 남의 지도: 프로필 이미지
- 내 지도: 공유 버튼
```
이 보이도록 수정
- dev에 한꺼번에 머지되면 LifeMapContent 컴포넌트 적절하게 분리하면 좋을 것 같습니다~
=> fix: 남 지도에서 공유 버튼을 -> 프로필 이미지로 변경

src/features/goal/components/detail/emoji/Reaction.tsx, src/hooks/reactQuery/emoji/useGetEmojiByGoal.ts
👇 한명이 모두 누른 이모지임에도, 총 이모지 개수로 count를 하고 있었어유
- 서버에서 `totalReactUserCount` 값 추가해줘서 적용했슴다
- 저 부분이 뭔가 클릭이 가능하다는 게 인지가 잘 안 되는 거 같아서
- 다원스에게 피그마로 알리긴 했는데, 다시한번 노티하구 변경되면 또 반영한 PR로 찾아올게유
=> bug: 이모지 totalReactUserCount 값 추가 및 적용

src/app/home/[username]/layout.tsx, src/app/my/layout.tsx, src/features/home/components/homeTab/HomeTab.tsx, src/features/home/components/lifeMap/LifeMapContent.tsx, src/features/home/components/lifeMap/LifeMapInfo.tsx, src/features/home/components/lifeMap/Map.tsx
- close #218 
1.  지도 탭 / ~~피드 탭~~ 추가
2. 피드 탭 추가로 인해 `LifeMapContent` 컴포넌트가 복잡해져서 지도 탭에 해당하는 컴포넌트 분리했섭니다
- `LifeMapContent` = 지도 탭 + 피드 탭
- 추후에 기존에 있던 컴포넌트명 수정이 필요합니다.. 
https://github.com/depromeet/amazing3-fe/assets/80238096/21f735fc-f453-42d1-a5ea-2cbd7c13f6ef
=> feat: 홈 화면 - 지도 탭 추가

src/features/feed/FeedBody.tsx, src/features/feed/feedCard/FeedCard.tsx, src/features/feed/feedCard/FeedCardBody.tsx, src/features/feed/feedCard/reactionGroup/Emojis.tsx, src/features/feed/feedCard/reactionGroup/ReactedEmojiButton.tsx, src/features/feed/feedCard/reactionGroup/ReactionGroup.tsx, src/hooks/reactQuery/emoji/useCreateEmojiForFeed.ts, src/hooks/reactQuery/emoji/useDeleteReactedEmojiForFeed.ts, src/hooks/reactQuery/goal/useGetGoalFeeds.ts
- 피드 페이지 API 연결
- 변경된 /goal/explore 적용
- 이모지 API 추가
- 이모지 API에서 요청 성공시 invalidateQueries를 이용하여 데이터를 갱신하도록 구현
음.. 피드 이모지 관련 API 아직도 고민이긴 함...
- 현재 피드 페이지에서 이모지 추가 / 삭제시 React-Query의 `invalidateQueries`를 사용하여 현재까지 캐싱된 피드 데이터를 모두 다시 불러옴
- 예) 무한 스크롤 페이지 단위가 10개이고, 30번째 목표까지 화면에서 본 이후, 이모지 추가를 하면 30개에 대한 데이터를 새로 요청
- 이를 개선하기 위해 처음 생각했던 것이 콜백함수를 통해 업데이트할 목표피드를 찾아 리액션 부분을 업데이트하는 것.
- 아직 오류가 있어 완벽히 구현하진 못하였지만 낙관적 업데이트를 통해 구현 가능할 것 같음. 하지만 이 또한 목표를 찾는 로직과 객체 복사로 인한 연산에 대한 오버헤드가 발생
- 또 다른 방법은 서버로부터 피드 데이터를 응답 받은 후, 각 피드에 대한 카드 컴포넌트에서 이모지 관련 데이터를 요청하여 각각의 서버 상태를 관리
- 즉, 피드의 무한 스크롤의 페이지 단위가 10개라면, 해당 페이지를 불러올때 10개의 목표에 대한 이모지 데이터를 추가로 요청
- 화면 렌더링시 많은 요청이 가기는 하지만 피드 이모지 추가 / 삭제에 대한 요청은 간단함
https://github.com/depromeet/amazing3-fe/assets/45158550/aaae91e9-3ba0-4823-b032-4f9a28f8b4ca
- 모바일 환경에서 이모지 선택창의 …
=> feat: 피드 페이지 API 연결

src/components/atoms/bottomSheet/style.css
- 바텀시트 위로도 하단탭바가 올라가서 버튼이 가려지는 문제 있었어유
|:--:|:--:|
| <img src="https://github.com/depromeet/amazing3-fe/assets/112946860/e9c9ac1a-da30-4bfc-90ba-b89f35a119af" width="400" /> | <img src="https://github.com/depromeet/amazing3-fe/assets/112946860/a66b190f-c015-4311-b731-7c203c32a9d3" width="400" /> |
- N/A
=> fix: 바텀시트에 하단탭바가 올라가는 이슈 해결

src/features/cheering/Cheerer.tsx, src/features/home/components/lifeMap/PublicLifeMapBottomArea.tsx, src/hooks/reactQuery/cheering/useGetCheerer.ts
-  응원한 사람 조회 api 응답 값 수정 반영
- 응원하기 성공 시에도 에러 토스트가 뜨는 버그 수정
- `cursor`: 페이지 내 마지막 응원한 사람의 cheeringAt
- `cursor`: 서버에서 보낸 `nextCursor` 값 사용
---
https://github.com/depromeet/amazing3-fe/assets/80238096/29742fb6-d9f7-4611-ba6d-72fdf969ac59
- 이거 더 좋은 방식 아는 사람 있으면 .. 나도 알려줘 ..
-
=> feat: 응원한 사람 조회 api 응답 값 수정 반영 / 응원하기 성공 시에도 에러 토스트가 뜨는 버그 수정

src/hooks/reactQuery/goal/useGetTimeline.ts
- 다른 사람 타임라인 조회 시에도 동일한 타임라인만 조회되는 이슈 수정
- 타임라인 조회 쿼리 키 수정
- 타임라인 조회 쿼리 키가 사용자 이름에 따라 변경될 수 있도록 수정
-
=> fix: 다른 사람 타임라인 조회 시에도 동일한 타임라인만 조회되는 이슈 수정

src/features/goal/components/detail/emoji/ReactionUserTotalCount.tsx
- [XX 외 몇 명이 반응했어요 UI에서 닉네임 2글자 → 3글자까지 보이도록](https://www.notion.so/depromeet/XX-UI-2-3-4913a6ecdb614696a1814f14a787ab95?pvs=4)
- [내 이모지 누른사람 박스에서 좌측 프로필 위치 고정, 프로필과 텍스트 마진 유지](https://www.notion.so/depromeet/136e48c479c848478b1a09b6c16507d9?pvs=4)
|:--:|:--:|
| ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/e1b66abe-eacf-4c94-bdd7-997044d0b66c) | ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/8e85be9b-c0a5-47b9-bdb8-ed0b9f4b5f4a) |
- N/A
=> chore: ReactionUserTotalCount 컴포넌트 디자인 반영

src/components/atoms/toast/ToastProvider.tsx
- [댓글을 삭제했어요 토스트가 바텀시트 뒤에 뜨는 이슈](https://www.notion.so/depromeet/1cdc027cbecb41b19d6b6f65a1384447?pvs=4)
- `z-index` 늘리는 걸로 대응했는데.... 우리 999 이하로 사용하기로 약속해유 🤝...
- 더 좋은 방법 환영합니다...😓
=> bug: 바텀시트 뒤로 toast가 뜨는 문제 해결

src/hooks/reactQuery/comment/useCreateComment.ts, src/hooks/reactQuery/comment/useDeleteComment.ts
- [타임라인 댓글 작성 / 삭제 시, 댓글 개수가 반영되지 않는 이슈 수정](https://www.notion.so/depromeet/e4ba1950fb7142daaf388dcf2bbbae83?p=fe7e438732b143c384f1695803591091&pm=s)
- 댓글 작성 시, 낙관적 업데이트 적용
- 댓글 삭제 시, 캐시 값 수정
- 댓글 삭제 시, 다른 쿼리에 낙관적 업데이트 적용하고 있어서 setQueryData로 했는데 댓글 작성 시에도 setQueryData로 통일할까 고민 중..🫨
https://github.com/depromeet/amazing3-fe/assets/80238096/67eab62b-e5ee-41fa-b4fa-47ac53c866c0
- 현재 타임라인 api 수정 중이라 pull 받아서 테스트하면 댓글 개수가 정상적으로 안보일 수 있음
=> bug: 타임라인 댓글 작성 / 삭제 시, 댓글 개수가 반영되지 않는 이슈 수정

src/constants/date.ts, src/constants/index.ts, src/features/goal/components/new/DateForm.tsx, src/features/goal/components/new/DateInput.tsx, src/features/goal/utils/date.ts, src/features/member/components/new/BirthInputForm.tsx, src/features/my/components/update/UpdateForm.tsx, src/hooks/index.ts, src/hooks/useDateInput.ts, src/utils/date.ts
- 변경된 생년월일 입력 부분 디자인 반영 ([figma](https://www.figma.com/file/hREAodauJnxgE6SBuF0ZYR/UI%2FDesgin-system?node-id=2528%3A32255&mode=dev))
- 사용자가 입력을 시작하면, 유효성 검증할 수 있도록
- https://github.com/depromeet/amazing3-fe/pull/233 👈 요거 망가져서 똑같이 다시 올려유
=> refactor: 생년월일 입력 - 변경된 디자인 적용 및 리팩터링

src/features/goal/components/new/DateInput.tsx, src/features/goal/utils/date.ts, src/features/my/components/update/UpdateForm.tsx, src/features/my/contexts/UpdateMemberDataFormProvider.tsx, src/hooks/reactQuery/auth/useUpdateMemberData.ts, src/utils/date.ts
- [마이페이지에서 내 정보 수정 눌렀을 때 생년월일 비어있는 경우 저장 버튼 활성화가 안 됨](https://www.notion.so/depromeet/6629b243a0584c4aa6bab37ee2d6146a?pvs=4)
추가로, 아래 경우에 요청이 허용됩니다
- birth 제거
- birth가 없는 상태, 다른 필드 수정
🚨 `birth 값 길이 > 0` 이라면 유효성 검사
|:--:|:--:|
| <img src="https://github.com/depromeet/amazing3-fe/assets/112946860/0e4b8ea7-3954-4088-a248-55e5657391fe" width="400"  />| <video src="https://github.com/depromeet/amazing3-fe/assets/112946860/5d75fcf8-d1b5-404b-9ac2-5d51873f5434" /> |
- N/A
=> bug: 정보수정 페이지에서 birth 없이 수정 가능하도록

src/features/feed/feedCard/reactionGroup/ReactedEmojiButton.tsx, src/hooks/reactQuery/emoji/useCreateEmojiForFeed.ts, src/hooks/reactQuery/emoji/useDeleteReactedEmojiForFeed.ts
- 피드에 이미 존재하는 이모지를 + 버튼을 이용해 추가할 경우, 내가 반응한 이모지로 표기되지 않는 현상
- 불필요한 상태가 존재하여 삭제하고, 캐싱 데이터를 바로 상태로 사용하였습니다.
- API 요청 후, 캐싱 데이터 수정 로직을 리팩토링했습니다
|:--:|:--:|
| <video src="https://github.com/depromeet/amazing3-fe/assets/45158550/d5ad490e-a920-49ef-b374-166323e4ab97" /> | <video src="https://github.com/depromeet/amazing3-fe/assets/45158550/1352e943-f62e-4b43-a105-96263a1a72d5" /> |
=> fix: 이미 존재하는 이모지를 + 버튼을 이용하여 새로 추가할 때 내가 반응한 이모지로 표기되지 않는 현상 수정

src/features/home/components/lifeMap/PublicLifeMapBottomArea.tsx, src/hooks/useThrottle.ts
- [응원하기 버튼 클릭 후, 모든 버튼이 눌리지 않는 버그 수정](https://www.notion.so/depromeet/6f5b2e4a8ec74d2788cbb1ca7c197651?pvs=4)
- 원인: 응원하기 버튼 클릭 후, 응원에 성공한 경우에는 계속 로띠가 남아있음
- 수정: 응원하기 버튼 클릭 후에는 로띠가 보이지 않도록 조건 수정
=> fix: 응원하기 버튼 클릭 후, 모든 버튼이 눌리지 않는 버그 수정

src/features/feed/FeedBody.tsx, src/features/home/components/timeline/PrivateTimeline.tsx, src/features/home/hooks/useUpdateFeedEmojiCount.ts, src/features/home/hooks/useUpdateTimelineCommentCount.ts, src/features/home/hooks/useUpdateTimelineEmojiCount.ts, src/hooks/reactQuery/emoji/useCreateEmojiForFeed.ts, src/hooks/reactQuery/emoji/useDeleteReactedEmojiForFeed.ts, src/hooks/reactQuery/goal/useGetGoalFeeds.ts, src/hooks/reactQuery/goal/useGetTimeline.ts, src/hooks/reactQuery/useOptimisticUpdate.ts
- 타임라인 이모지 추가 / 삭제 안되는 이슈 수정
- 이모지 추가: 타임라인 api 호출
- 이모지 삭제: 낙관적 삭제
- 이모지 추가 방식는 총 2가지
- 1. 이모지를 눌러서 추가하는 방식 
- 2. `+ 버튼` 눌러서 이모지 추가하는 방식
- 1번은 기존 이모지 배열에서 해당 emojiId의 count를 늘려주는 방식으로 낙관적 업데이트 가능
- 2번의 경우, 기존 이모지 배열에 없는 새로운 emojiId가 추가될 수 있음
- 이모지 추가 시, 서버 응답으로 이모지 정보를 넘겨주고 있지 않아서 낙관적 업데이트 불가능
https://github.com/depromeet/amazing3-fe/assets/80238096/4ebac255-da9e-4a53-8560-a1106f3531e4
- 이미 존재하는 이모지인데 `+버튼`을 눌러서 동일한 이모지를 누르는 경우, 서버 500에러 발생
=> fix: 타임라인 이모지 추가 / 삭제 안되는 이슈 수정

src/components/atoms/input/Input.tsx, src/utils/composeEventHandlers.ts
- `<Input>` 컴포넌트를 보면 onFocus나 onBlur같은 이벤트 핸들러들에 대해 주입 받은 것들은 처리하지 않고 있었음
- `composeEventHandlers`를 추가해서 적용했어유 (참고: [radix-util](https://github.com/radix-ui/primitives/blob/main/packages/core/primitive/src/primitive.tsx))
```tsx
// Usage
onFocus={composeEventHandlers(onFocusFromProp, () => {
// 내부에서 처리하고 있는 로직
})}
```
- N/A
=> feat: composeEventHandlers 추가

src/features/comment/AddCommentInput.tsx, src/features/comment/BottomSheet/Layout.tsx
- [댓글 바텀시트 키패드 위치 의도대로 동작 X → 페이지뷰로 전환](https://www.notion.so/depromeet/X-88e0785d31f64a339aa340f939822024)
- 👆 위 노션 페이지에 재연 동영상 있는데
- 모바일에서 맨 처음에 `focus가 되었음에도 키패드가 올라오지 않는 게` 제일 큰 애로사항이여서
- 처음에 focus가 되지 않도록 하였고, focus되었을 때 viewport 조작할 수 있도록 수정해줬어유
- 이거 반영되었는데도 사용감에 큰 불편함이 있다면 페이지뷰로 넘어가겠습니다...
- `😓 페이지뷰 한다면서..`
- 댓글 바텀시트 사용처가 많아서 그런지 페이지뷰가 차암..아쉬워서 미련을 못 버린채 한번만 츄라이 해보았어요
https://github.com/depromeet/amazing3-fe/assets/112946860/247a6386-35a5-4ee8-a538-b3d8e9deb28c
=> bug: commentBottomSheet 마운트 시 input focus 제거

src/components/molecules/reactHookForm/RHFDateField.tsx, src/features/goal/components/update/GoalUpdateForm.tsx, src/utils/date.ts
- 목표 수정 화면 날짜 수정 필드에 validation이 적용 안되는 이슈 해결
- number 타입에서 숫자 입력 시 maxLength 적용이 안되서 text 타입 + numeric inputMode로 변경
- maxLength 적용
- 반대로 적용된 isValidDate 수정
- date default값을 1로 수정 (0일 경우, 지난달 마지막 일로 변경됨..)
https://github.com/depromeet/amazing3-fe/assets/34956359/a3e2ef7e-37f6-425b-aa21-3430e5fb7c8e
=> fix: 목표 수정 화면 날짜 수정 필드에 validation이 적용 안되는 이슈 해결

src/components/atoms/avatar/Avatar.tsx, src/features/home/components/lifeMap/LifeMapContent.tsx
- [남의 지도 프로필 누르면 내 프로필로 이동하는 버그 수정](https://www.notion.so/depromeet/a610a98d8d294327ace67b0d0b46080f?pvs=4)
- 프로필에 링크 제거했습니다~
- 아무래도 내 지도에서 프로필 -> 공유버튼으로 변경되면서 요상하게 변경된듯합니다
- 아바타 컴포넌트에 `cursor: pointer` 속성이 있어서 클릭 가능한 요소처럼 보여서 제거했습니다~
- 아바타 컴포넌트를 링크나 버튼으로 사용하는 경우에는 한 번 래핑해서 사용하기 때문에 속성 삭제하는게 좋을듯합니다
https://github.com/depromeet/amazing3-fe/assets/80238096/e65b03b1-901b-4970-a0bf-549f5f31c248
=> fix: 남의 지도 프로필 누르면 내 프로필로 이동하는 버그 수정

src/features/feed/feedCard/FeedCardBody.tsx, src/features/goal/components/detail/DetailHeader.tsx, src/features/goal/components/update/GoalUpdateForm.tsx, src/features/home/components/MapCardCollections/MapCard.tsx
- [Goal Page에서 뒤로 가기하면 지도 navigation이 첫 페이지로 가버림](https://www.notion.so/depromeet/Goal-Page-navigation-9fe3c08de2504280906f395b00436e89?pvs=4)
- [피드 → 세부목표 → 돌아가기 클릭 시 지도로 가버림](https://www.notion.so/depromeet/5f53ad00e7834fae9985da54d89f8312?pvs=4)
- goal detail 화면에 previous 경로와 popState 커스텀 동작 추가
https://github.com/depromeet/amazing3-fe/assets/34956359/56a0bc9a-7adf-46b0-a97c-7f10730b4433
=> fix: goal detail 화면의 navigation이 비정상 동작하는 이슈 해결

src/app/oauth2/token/page.tsx, src/components/molecules/loginIconSet/LoginIconSet.tsx
- 남의 지도에서 로그인 유도 화면을 통해 로그인 시 마이 페이지로 이동하는 이슈 해결
- login 페이지 이동 전에 현재 페이지 path를 저장하고 로그인 성공 시 redirect 수행
- localhost에서는 로그인 안했을 때 home 페이지로 접근하면 서버에서 500 던지네요;; 일단 코드에서 현재 경로 수정해서 테스트 했습니다. dev로 반영 후 다시 확인해 보겠습니다~
https://github.com/depromeet/amazing3-fe/assets/34956359/08781802-b0e0-4a47-9661-e0cacaf5b865
=> fix: 남의 지도에서 로그인 유도 화면을 통해 로그인 시 마이 페이지로 이동하는 이슈 해결

src/features/home/components/homeTab/HomeTab.tsx, src/features/home/components/lifeMap/LifeMapContent.tsx, src/hooks/useUpdateQueryString.ts
- [타임라인에서 새로고침 시 지도 페이지로 이동하는 이슈 수정](https://www.notion.so/depromeet/c35d7275f4e9449a8c82b677a4ed6592?pvs=4)
- 탭 상태를 `useState`에서 -> `쿼리스트링`으로 변경
- AS-IS: 탭 상태를 `useState`로 관리하기 때문에 새로고침 시 탭의 초기 값인 지도 페이지로 변경됨
- TO-BE: 탭 상태를 `쿼리스트링`으로 관리해서 새로고침 시에도 유지될 수 있도록 수정
https://github.com/depromeet/amazing3-fe/assets/80238096/1c6c0ff3-6d4b-4167-9051-e35c020c6577
=> fix: 타임라인에서 새로고침 시 지도 페이지로 이동하는 이슈 수정

src/features/feed/feedCard/FeedCard.tsx, src/features/feed/feedCard/FeedCardBody.tsx, src/features/goal/components/detail/DetailHeader.tsx, src/features/goal/components/update/GoalUpdateForm.tsx, src/features/goal/components/update/GoalUpdateHeader.tsx
- Feed를 통해 들어간 다른 사람의 목표에서 삭제/수정 버튼이 생김.
- 수정 기능 화면에서 뒤로 가기 클릭 -> 목표에서 뒤로가기 클릭 -> 항상 지도 화면으로 돌아감.
- detail 경로에 들어갈 때 목표의 currentUser 값 변경
- 뒤로가기 기능 경로 수정
https://github.com/depromeet/amazing3-fe/assets/34956359/85a479d6-3703-48e7-9372-6aef3bfa3659
=> fix: 남의 목표에서 삭제/수정 버튼이 생기는 이슈 해결 (+ 수정 기능 뒤로가기 경로 수정)

src/components/molecules/contentWrapper/ContentWrapper.tsx, src/features/home/components/lifeMap/LifeMapContent.tsx
- 양쪽 여백이 없어 답답하게 느껴졌어유
|:--:|:--:|
| ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/0403cf12-2d93-4f2b-a146-c09a99d4f19f) | ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/2584d049-e123-4cb4-a895-84b2688d5f46) |
- N/A
=> fix: 모바일뷰에서 양쪽 여백이 없어 답답해 보이는 문제 해결

src/hooks/reactQuery/goal/useGetPublicTimeline.ts, src/hooks/reactQuery/goal/useGetTimeline.ts
- page 값에 NaN가 전달되는 이슈 발견
- initialPageParam에 null 대신 0 입력
정상 동작 확인 (근데 dev 환경에서 frontend는 null이든 0이든 똑같이 동작해서 서버나 DB 문제일 듯..?)
=> hotfix: initialPageParam에 null 대신 0을 입력

src/components/atoms/avatar/Avatar.tsx, src/components/molecules/comment/Comment.tsx, src/features/emoji/BottomSheet/ReactUser.tsx
- https://github.com/depromeet/amazing3-fe/issues/278
- https://github.com/depromeet/amazing3-fe/issues/280
- `Avatar` 컴포넌트 사용
- `Avatar`에서 href 제거
- 이유: 프로필 이미지에서만 href를 사용하는 경우보다는 nickname과 감싼 div에서 Link를 주는 경우가 더 많을 것 같아 제거했어용
close #278
close #280
=> fix: 이모지 바텀시트에서 프로필 이미지가 길어지는 문제 해결

src/components/atoms/input/Input.tsx, src/features/goal/components/new/DateInput.tsx
- https://github.com/depromeet/amazing3-fe/issues/285
|:--:|:--:|
| ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/77f7e2f4-90b3-408a-8da9-f611eb737db7) |  ![image](https://github.com/depromeet/amazing3-fe/assets/112946860/dfca5d23-1415-4ac4-8557-9fea7cf08d8f) |
- ㅋㅋㅋㅋ 이거 없어서 인풋류 초기값 다 문제 있었을텐데 아무도 몰랐던게 개콘이다~
close #285
=> fix: 빠진 value prop 추가
